### ISSUE TITLE
Nuget Version Issue 

### ISSUE THREAD

**Issue by bhavneetsinghthakur** [xBimTeam/XbimWindowsUI#1]
Currently in Nuget we have this four Version DLL

  package id="Xbim.Essentials" version="3.0.3" targetFramework="net45" 
  package id="Xbim.Exchange" version="3.0.0-Prerelease" targetFramework="net45" 
  package id="Xbim.Geometry" version="3.0.3" targetFramework="net45" />
  package id="Xbim.Scripting" version="3.0.0-Prerelease" targetFramework="net45" 

But at time of Auto Restore in WindowsUI project It Found Higher Version Of Dll
Where I get That Dll

**Comment by LloydPickering** [comment]
Our CI is building packages to the feed at https://www.myget.org/F/xbimtest/ it might be there.

**Comment by bhavneetsinghthakur** [comment]
Hi LloydPickering

When you will launch latest Xbim Source in market  ?
