### ISSUE TITLE
Open File from Server

### ISSUE THREAD

**Issue by SIBIMMS** [xBimTeam/XbimWindowsUI#103]
Greetings,
I have a question regarding what would be the best option to open a ifc stored on a server.
I was thinking about creating a temp file and then open it, but this might bring some problems if i don't want that the person to keep the file (as he can go to the temp folder and find the file). Is there a better way to do this?
Thank you

**Comment by andyward** [comment]
Can you clarify what you mean in terms of 'stored on a server'? Is that a Web server, where you want to let users upload and work with IFC over HTTP? Or do you just want a native client (e.g. on a Windows machine) to open an IFC from a networked server?

The two have very different approaches / solutions.

**Comment by SIBIMMS** [comment]
Basically we want to have a online server (we sould have a private machine for that), where we would store IFC files, and then we would like a native client to be able to open an IFC file stored on that server. This would let people from my company (which are located in multiple countries) to view ifc files without us having the trouble to send them to everyone.
The way i thought of doing this was to download the file on realtime and then open it. The thing is, due to security reasons, we don't want the file to be stored on the computer so it would be nice if it was possible to open the IFC without downloading it to the computer.

**Comment by andyward** [comment]
**Option 1**: Convert IFCs to XBIM (Esent) format on the server, and send this over to the native client
**Option 2**: Stream the IFC over the network, and use the Stream overload of [IfcStore.Open](https://github.com/xBimTeam/XbimEssentials/blob/307fee4940db19b8fe0ea509ccd4a5875006d473/Xbim.Ifc/IfcStore.cs#L214) (so the file never explicitly hits disk)

Neither are infallible. In fact they're trivial to circumvent...

On Option1: XBIM files are basically a full representation of IFC in our format and in fact anyone with XbimXplorer could convert it back to IFC again.

On Option2: If your app can access the original file over the network, a user can download it by other means. (via a browser or just a UNC path). It's just 'security by obscurity'.

This feels largely a limitation of any native client (An analogy would be opening *.docx in Word without accessing the document).

If you **have** to employ a native client, one option might be to use an embedded WebGL capable browser (https://cefsharp.github.io/) so you could use the [WebUI viewer](https://github.com/xBimTeam/XbimWebUI). Idea is you'd convert IFC to Wexbim and possibly some JSON on the server, and this is what gets downloaded to the client - not the IFC file.

Or just go all-in on the cloud service that does all this for you :)

**Comment by CBenghi** [comment]
@SIBIMMS,
The GlTF export library that we have might also be an option for you.
We can offer customisation around that if you are interested.
Best,
Claudio

**Comment by SIBIMMS** [comment]
Sorry for taking so long to reply to you all, but i don't work on this full time and had other priorities. So the best solution i found was to download an encrypted file to the employee's pc's and decrypt it only when the program is reading the file and encrypt it right after. Of course this is easily bypassed but i think that, in conjunction with a remote path, its enough for what we want.
Thank you all for your help

**Comment by andyward** [comment]
Yeah, I can't see us wanting to add password complexity to the store. 

You might have some luck using the `IfcStore.Open(Stream)` overload and using something like [System.Security.Cryptography.CryptoStream](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.cryptostream?view=netframework-4.7.2)

That way you'd not be leaving an unecrypted file on disk.
