### ISSUE TITLE
Problems exporting COBie from XBimExplorer

### ISSUE THREAD

**Issue by russmckay1** [xBimTeam/XbimWindowsUI#104]
Hello,

I have been using XBimXplorer for a number of years with no problems at all. Today, I tried to export COBie from an IFC file that I have used many times without any problems, but now, when I hit the Export button, nothing happens. I know that we don't get any feedback from actually pressing the export button, but now I can wait for ever and nothing happens.

My set up is Assembly version 4.0.0.0  file version 4.0.1092.15323 which was compiled on 15.02.2019.

I am using the XplorerPlugin.CobieExport 4.0.7-V00024

I am pretty sure that I am not doing anything wrong. The IFC that I am using has always worked in the past on this tool. I have several instances of XBimXPlorer on different machines and each machine is reacting in the same way.

Thanks for your help - Russ

**Comment by andyward** [comment]
Yep, looks like there's a rogue version of XbimXplorer floating about that's not compatible with the COBie plugin. Digging in..

**Comment by andyward** [comment]
Hi @CBenghi It seems there's a version of XbimXplorer 4.0.13-V004  pushed out through the Squirrel update mechanism which I can't trace back to an official build. Any idea where it's come from? It looks like it may have some binary compatibility issues with the V4 plugins. E.g. I'm seeing errors like then when exporting models to COBie with the legacy exporter:

`
==== 22:43	ERROR	Xbim.WinUI
Error exporting cobie from plugin.
Method not found: 'Void Xbim.Common.Geometry.XbimRect3D.Union(Xbim.Common.Geometry.XbimRect3D)'.
   at Xbim.COBie.Data.COBieDataCoordinate.Fill()
   at Xbim.COBie.COBieBuilder.Initialise()
   at Xbim.COBie.COBieBuilder.GenerateCOBieData()
   at XplorerPlugin.CobieExport.UI.COBieExport.ExportCoBie()
   at XplorerPlugin.CobieExport.UI.COBieExport.OK_Click(Object sender, RoutedEventArgs e)
`

Here's the reported Xplorer version. (I've not updated explicitly so assume it's the autoupdate)

![image](https://user-images.githubusercontent.com/923699/53918837-05cefc80-4060-11e9-8ead-b3c29af1bca1.png)

Here's my plugins

![image](https://user-images.githubusercontent.com/923699/53919375-be497000-4061-11e9-844b-a6f6a2aca196.png)

I get the above 'Method not found' error on CobieExport 4.0.7-V0024 and the latest (V0027)

**Comment by andyward** [comment]
Also @CBenghi  if you can could you add me to the xbim-plugins myget and point me at the Squirrel admin when you have a moment that'd be great. I've been meaning to push out a set of v5 Xplorer binaries for a while

**Comment by andyward** [comment]
This looks like the culprit. 

https://github.com/xBimTeam/XbimEssentials/commit/2abf8acec9cf47ad7b20621a2466917f47776461#diff-53d5538fff98336da7ac30df22a869d0

It's a breaking change that has been pushed out in Essentials 4.0.30-V053 to Myget Develop https://www.myget.org/feed/xbim-develop/package/nuget/Xbim.Essentials/4.0.30-V053

.. which is included in a v4.0 maintenance build of Xplorer at https://github.com/xBimTeam/XbimWindowsUI/commit/4b77f8c3a62bea8a0caae7948b6d2540fd91e415#diff-16463a26e75eed4f38776161d429f1a4

And this has been published to the Squirrel auto update mechanism.

... but the plugins in https://github.com/xBimTeam/XbimExchange/blob/maintenance/Xbim4.0/Xbim.COBie/Data/COBieDataCoordinate.cs are still referencing the old version of Xbim.Common where `XbimRect3d.Union` is expecting to return `void`

Possible resolutions?

* Revert the Xplorer change and republish
or
* add a shim to XbimRect3D to retain backward compatibility, propagate & republish
or
* call it a day on v4 builds, put out v5 Xplorer & plugins which should auto-update. 

I favour the latter. It'll be simpler to be working in maintenance branches - I'm not sure how we're planning to fold these changes into v5 as it is.

**Comment by CBenghi** [comment]
@andyward,
I'll investigate and come back to you tomorrow.

**Comment by CBenghi** [comment]
@russmckay1, 

please, have a look at the updated version of the plugin. 
The problem should be fixed.

@andyward, I've given you admin permissions on the plugin feed.
Also, with regards to the possible solutions that you mention, I think the ideal is the latter too, but it might take a little bit of thinking.

I'm back from Amsterdam in the last week of March, and I'd like to meet you and @SteveLockley to plan the steps ahead... 
Hopefully this patch will bridge us till then, but if you are in a rush I'll be happy to have a skype call sometimes this week.

@russmckay1, please close the issue if this is resolved for you after the plugin update.
Claudio

**Comment by russmckay1** [comment]
Hi xBIM Team,

Fantastic job in record time - THANKS!!! - All fixed now.

Another question - I know it's probably a known feature, but why don't we 
get any feedback when we hit the export button on the BIM export?

Regards - Russ

**Comment by andyward** [comment]
@russmckay1 Good stuff. The COBie Exporter is a plugin module, so we'd have to put some kind of acknowledgement in [there](https://github.com/xBimTeam/XbimExchange/tree/maintenance/Xbim4.0/XplorerPlugin.CobieExport/UI). Ideally you'd get some progress as it goes, but I suspect that requires some plumbing work between the Xplorer plugin system and its plugins.

Rather than a model dialog, I'd be inclined to launch Explorer with the file location highlighted when the export is done to save you hunting it down.

**Comment by andyward** [comment]
@CBenghi Yes, I'm around end of March. Will ping you an email.
