### ISSUE TITLE
Generic Models and special equipment display not proper

### ISSUE THREAD

**Issue by satregiftc** [xBimTeam/XbimWindowsUI#105]
Hi ..

i have a issue with display of special equipment and generic models display in viewer
please find the attached images comparing with revit and please advise how to resolve
this issue

Regards
Satish
![cars_viewer](https://user-images.githubusercontent.com/33161851/54023939-4e9bc800-41bc-11e9-9200-ca2891fa42e7.png)
![cars_revit](https://user-images.githubusercontent.com/33161851/54023940-4f345e80-41bc-11e9-9cb0-1e1cc19c95ff.png)
![fireexit_viewer](https://user-images.githubusercontent.com/33161851/54023942-4f345e80-41bc-11e9-9e7b-13a868698580.png)
![fireexit_revit](https://user-images.githubusercontent.com/33161851/54023943-4f345e80-41bc-11e9-840b-d5e25419a4ba.png)

**Comment by andyward** [comment]
Moved over from Web, as it's obviously manifested in Xplorer

**Comment by andyward** [comment]
I suspect the fundamental issue is that materials are never typically exported in IFC, and the viewer is just defaulting a colour/material.

We'd have to take a look at the RVT to see exactly how it's modelled and whether there's anything that can be done on IFC export or in XBIM

**Comment by CBenghi** [comment]
I'd have to see the IFC files to be able to see if there's any information in the model that we can use.
It does look like there's some promising weird pixel on the sign, from the screenshot.
@satregiftc can you share a small revit/ifc pair to look into?
Please try to reduce it to the minimal model that demonstrates the issue.

Thanks

**Comment by satregiftc** [comment]
Hi..

Thank you .. Andyward and Benghi
Please find the attached ifc and rvt file with a sample equipment


[Speceqip.zip](https://github.com/xBimTeam/XbimWindowsUI/files/2950855/Speceqip.zip)

Thank you 
Satish

**Comment by CBenghi** [comment]
Hello @satregiftc,
I've looked into the ifc files and it does look like we are respecting the stated styles.

Curiously the geometry is there, so if I force a different colour I get the image as follows:
![image](https://user-images.githubusercontent.com/5476273/54274547-a48bb980-4588-11e9-9073-759d6ccab424.png)

But if you follow the property chain down from any of the mapped items you can see that all elements in the exit sign point to the same style and colour. This is a problem that you should notify to the IFC Exporter in revit.

If you try to impart the following commands in xplorer you will see the data 

```
se 415858 Representation Representations Items MappingSource MappedRepresentation Items StyledByItem Styles Styles Styles SurfaceColour
se 417204 Representation Representations Items MappingSource MappedRepresentation Items StyledByItem Styles Styles Styles SurfaceColour
```

**Comment by satregiftc** [comment]
Thank you Benghi..
We will check it..

Regards
SAtish
