### ISSUE TITLE
wrong geometry read display

### ISSUE THREAD

**Issue by tulip411** [xBimTeam/XbimWindowsUI#107]
I recently opened an IFC file with XBimWindowsUI, and the wall in the model seems to be wrong.

The model it should look like:
![kit](https://user-images.githubusercontent.com/46897676/55949797-b75ee000-5c53-11e9-824e-2ca10f3f79e8.PNG)

What it looks like in Xbim:
![xbim](https://user-images.githubusercontent.com/46897676/55949834-cd6ca080-5c53-11e9-94e9-6700f272b4ea.PNG)

Seems that there are some mistakes in reading IFCBOOLEANCLIPPINGRESULT

**Comment by andyward** [comment]
Yes, this was fixed in https://github.com/xBimTeam/XbimGeometry/issues/158 which should have been propagated to WindowsUI in 87e33a9f61469caa7a8a8af81a33eb7a97e8f943

Make sure you've pulled the latest.
