### ISSUE TITLE
Crashing on selecting materials tab for IfcBuilding

### ISSUE THREAD

**Issue by Noranius** [xBimTeam/XbimWindowsUI#112]
For testing I used you ifc file "4walls1floorSite.ifc" If I select the building (#89) and then the materials tab the whole application crashes. Maybe this issue is related to Issue 86?

Used branch ifc_rail

[4walls1floorSite.zip](https://github.com/xBimTeam/XbimWindowsUI/files/3166173/4walls1floorSite.zip)

**Comment by CBenghi** [comment]
I could not reproduce on IfcRail, but I've posted a fix for maintenance/Xbim4.x 
See: https://github.com/xBimTeam/XbimWindowsUI/commit/4fe8ce409e413c08741a91e40204575244159ca5

**Comment by Noranius** [comment]
Works :)
