### ISSUE TITLE
Error at visualization of IfcSectionSolidHorizontal

### ISSUE THREAD

**Issue by Noranius** [xBimTeam/XbimWindowsUI#114]
Getting an error while parsing a file within xbim XPlorer:

```
Xbim.ModelGeometry.Scene.Xbim3DModelContext
GeomEngine: #441="IfcSectionedSolidHorizontal" 
["Geometry Representation of Type IfcSectionedSolidHorizontal is not implemented"]

```
Used Version: Compiled from IfcRail-Branch

Example file, see attachement

[SuspensionFootbridge_4x2_corrected.zip](https://github.com/xBimTeam/XbimWindowsUI/files/3176802/SuspensionFootbridge_4x2_corrected.zip)

**Comment by andyward** [comment]
As you've discovered, The ifcRail branch only has a partial & limited implementation of the IfcAlignment geometries. I've tried to summarise the state of things at xBimTeam/XbimGeometry#181

If you take a look at the buildingSmart spec for [IfcSectionSolidHorizontal](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/schema/ifcgeometricmodelresource/lexical/ifcsectionedsolidhorizontal.htm) it's not trivial. 
It's going to take some effort to implement those geometries I suggest, so any help welcome!

Thanks for the sample model. 

As this isn't the repo for Geometry issues, I suggest we close here, and track 181 instead.
