### ISSUE TITLE
Can i hide some IfcElement in the model view

### ISSUE THREAD

**Issue by azura-vergo** [xBimTeam/XbimWindowsUI#12]

**Comment by CBenghi** [comment]
Hello,
the way in which elements are currently grouped in layers for efficiency reasons does not provide an easy way to show/hide individual elements.
You can 
You can write your own layerstyler that allows that although sometime this would mean that the whole geometry needs to be reloaded.
We are considering the development of better 3D API's in the next few months.
I'd be happy to help you develop your LayerStyler if you need to.
Claudio

**Comment by azura-vergo** [comment]
oh i get.
thank you very much
