### ISSUE TITLE
Can not restore the nuget packages

### ISSUE THREAD

**Issue by Edassap** [xBimTeam/XbimWindowsUI#121]
I just clone the newest version of mater, and try to compile it.But there are problems when restore the packages dependencies. I installed the vs2017, framework4.7, framework4.72 and netstandard2.0, netstandard2.1. 
Here is the picture
![image](https://user-images.githubusercontent.com/16076576/61230819-6cc29780-a75d-11e9-8a54-43166dba7393.png)

And I wonder why . hope Some Lord can help me .urgent......

**Comment by andyward** [comment]
If memory serves that issue:
> ".." can only be added at the beginning... 

was a problem with old versions of Nuget. Make sure your visual studio is up to date. 

Also try doing a `nuget restore <solution>` from a command prompt or powershell

**Comment by Edassap** [comment]
Thank you! It really was! And I update nuget vesion and restore vs ,it worked!
