### ISSUE TITLE
how to view ifc model in xBim on .Net Framework 4.8

### ISSUE THREAD

**Issue by nikhilpatil359** [xBimTeam/XbimWindowsUI#126]

**Comment by nikhilpatil359** [comment]
after installing the xBIM Geometry nugets package it includes microsoft.extension.logging 2.1.1 as dependencies and it does not work with net47 so can't able to access the sample code provided by the above link.

**Comment by nikhilpatil359** [comment]
please check and provide the solution for it

**Comment by andyward** [comment]
Check you have the latest .net runtimes installed? Microsoft.Extensions.Logging 2.1.1 targets .netstandard2 which should run file on net47.

If it doesn't please can you provide more precise details of any error.

**Comment by nikhilpatil359** [comment]
We are trying to install the latest nugets packages of xBIM on microsoft visual studio 2015 (.Net Framework 4.7 Used) ... but it is not getting installed and throwing error as "microsoft.extension.logging 2.1.1 does not work with 4.7"

![xbimBugs](https://user-images.githubusercontent.com/51161827/65027499-14279a80-d958-11e9-887c-580e8a053182.jpg)

**Comment by andyward** [comment]
I don't think we support VS 2015 [any more.](https://github.com/xBimTeam/XbimWindowsUI/blob/master/README.md#compilation) You _might_ get away with it if it's the latest (run the VS Installer and check for updates). 

But my recommendation is to use VS2017 or 2019.  Using old VS versions will just cause issues
