### ISSUE TITLE
Reconstructing IfcStandardWall using 'Axis' Curve2d Representation and Material offsets

### ISSUE THREAD

**Issue by Belrius** [xBimTeam/XbimWindowsUI#129]
Hi guys, software's working perfectly but I didn't know where else to ask this. Thought maybe someone here might know.

Instead of using the SweptSolid representation of a IfcStandardWall I'd like to rebuild it using the materials plasterboard / frame / void / brick etc because I'm trying to do cutaways in my software (amongst other things).

So I take the normal to the wall axis direction and extend that by the material width. this works beautifully in about half the situations, but in the other half the normal is pointing the wrong direction and so the wall is placed *beside* where it is supposed to be. 

I can't seem to see how to flag when to flip the normal. I can do it manually and everything that's currently right becomes wrong, and everything that's wrong becomes right.

Hoping someone has seen this before and can help, or can suggest a more appropriate location for this question.

Many thanks
Andrew

**Comment by andyward** [comment]
Hi @Belrius this sounds like a geometry issue rather than a Windows Explorer issue.

I'd not be surprised if it's related to https://github.com/xBimTeam/XbimGeometry/issues/96 but @SteveLockley would be best placed to investigate

**Comment by SteveLockley** [comment]
Hi Belrius, I am assuming you are defining your wall in IFC not in xbim geometries, if you are not then that is the way to go. If you are then you can use IfcCompositeProfileDef [https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/schema/ifcprofileresource/lexical/ifccompositeprofiledef.htm](url) to model the footprints of the floor as a set of closed profiles sitting side by side at the foot of the wall, these are then all extruded as a single IfcExtrudedAreaSolid. Look at one of our test files for an example of how to build the IFC [https://github.com/xBimTeam/XbimGeometry/blob/master/Xbim.Geometry.Engine.Interop.Tests/TestFiles/CuttingOpeningInCompositeProfileDefTest.ifc](url). After this just send the IFC to the geometry engine and it will do the work for you.

**Comment by Belrius** [comment]
Oh shoot, thank you Andy, you're right. I've posted in completely the wrong place :(. My apologies :(

Thank you very much for your reply Steve. I will look into the techniques you described.  

I should have lead with what I'm trying to do, which is to reconstruct a home exported from Archicad, however with a bunch of my own set of parametric modifications to it. It's making it difficult to just use the output of the geometry engine. This is leading me towards some wheel reinvention but I'm not sure how to get around it for what I need to do. :/
