### ISSUE TITLE
issus in .net framework 4.0

### ISSUE THREAD

**Issue by azura-vergo** [xBimTeam/XbimWindowsUI#13]
Hi,
when i try to run the XbimWindowsUI base on .net framework 4.0,
there was a lot of bug
such as:
1.XML namespace "clr-namespace:PropertyTools.Wpf;assembly=PropertyTools.Wpf" no exist mark "EnumMenuItem"
2.can not idetify or access member “ExportCoBieCmd”
![qq 20151116181116](https://cloud.githubusercontent.com/assets/8624914/11179326/9147367c-8c8d-11e5-9b22-97f53f9fc667.png)

I hava download all the package

**Comment by CBenghi** [comment]
Hello,
as far as I know the code should compile without problems.
I think the problem could be due to your computer failing to download all the required nuget packages.
Can you check that?
Claudio

**Comment by azura-vergo** [comment]
thanks Claudio.
i have export all the nuget packages.
but it still have some problem
![qq 20151117202651](https://cloud.githubusercontent.com/assets/8624914/11211553/290b5e2e-8d6b-11e5-8862-21b20d13c6f9.png)

the first error is  -- “Xbim.Ifc2x3.Kernel.IfcProject” was Defined in the Assembly that is not referenced.
You must add references to Assemblies“Xbim.Ifc2x3, Version=3.1.0.0, Culture=neutral, PublicKeyToken=11e3655e576ec5a9”
![qq 20151117204919](https://cloud.githubusercontent.com/assets/8624914/11211802/f35413d2-8d6c-11e5-93e4-49fcfafdc0bb.png)

**Comment by CBenghi** [comment]
That's odd,
i'll look into that tomorrow, in the meanwhile can you try dowloading the develop branch from github?
Thanks,
Claudio

**Comment by azura-vergo** [comment]
thanks, i have download all the develop branch,except xBim BCF,because it needs .net4.5

**Comment by CBenghi** [comment]
I've published changes to develop and master now.
They should both work, including the bcf plugin at net40.
I'll close this issue, but let me know if you find any problems.

**Comment by azura-vergo** [comment]
I`m sorry, it still can not work

can not identify or access the member "CoBieClassFilter"
![qq 20151119094951](https://cloud.githubusercontent.com/assets/8624914/11260122/31f2915e-8ea3-11e5-8342-b4024dc823de.png)

namespace “clr-namespace:HelixToolkit.Wpf;assembly=HelixToolkit.Wpf” no exist sign "HelixViewport3D"
![qq 20151119095037](https://cloud.githubusercontent.com/assets/8624914/11260123/31f40142-8ea3-11e5-9f0c-1e0895d803a6.png)

FYI,BCF still can not download
![qq 20151119095105](https://cloud.githubusercontent.com/assets/8624914/11260191/d3df022c-8ea3-11e5-8990-21a22cbd4037.png)

**Comment by azura-vergo** [comment]
is it something wrong with my develop and master?
https://www.myget.org/F/xbim-master/api/v2
https://www.myget.org/F/xbim-develop/api/v2

**Comment by CBenghi** [comment]
Hello again,
I'm not sure I understand what you are doing.
I thought the problem was that you cannot compile Xplorer and that the problem with BCF was the one with the internal BCF plugin.
What you are showing now makes me suspect that you have tried to update all the libraries from nuget, and some of them are not compatible (e.g. tha latest essentials is using a different system).

Please try to download a fresh copy of windowsUI from github and compile it just as it is (do not update libraries from nuget).
Let me know if this works.

**Comment by azura-vergo** [comment]
hello
I`m sorry that not make it clear.this is my step how to compile Xplorer .
First,i download the XbimWindowsUI-master.zip,and unzip it.
second ,open it and change the target framework into 4.0 and then debug the XbimXplorer, i see the project Automatically download some package.
And then,there is show up some error,(i don`t why i can upload photos,so i copy the error)

XML 命名空间“clr-namespace:HelixToolkit.Wpf;assembly=HelixToolkit.Wpf”中不存在标记“HelixViewport3D”。
XML 命名空间“clr-namespace:HelixToolkit.Wpf;assembly=HelixToolkit.Wpf”中不存在标记“HelixViewport3D”。 
XML 命名空间“clr-namespace:PropertyTools.Wpf;assembly=PropertyTools.Wpf”中不存在标记“EnumMenuItem”。
XML 命名空间“clr-namespace:Xbim.Presentation;assembly=Xbim.
XML 命名空间“http://schemas.Xbim.com/Presentation”中不存在标记“ScriptingControl”。

**Comment by CBenghi** [comment]
Xplorer has been targeting net40 for a long time.
I suspect you are using an old version of the library.
Try again but avoid the zip file.
Get the code directly using git from https://github.com/xBimTeam/XbimWindowsUI.git
You should clone the repository to a local folder and then compile it with no changes, it will already be on net40. Please keep me updated on progress.

**Comment by azura-vergo** [comment]
thank you so much,
i clone the code from git,and the target framework is 4.0
i think maybe ok this time,
something wrong with my nuget, i`m try to figure out.
thank you again.
