### ISSUE TITLE
[Question] How can I load the BCF plugin?

### ISSUE THREAD

**Issue by thmspl** [xBimTeam/XbimWindowsUI#134]
The list under `View > Settings > Plugins` is empty. There's nothing documented somewhere.

**Comment by andyward** [comment]
Have you switched to the 'development' list on the plugin settings page? By default it shows the installed plugins which will be empty initially.

E.g. 
![image](https://user-images.githubusercontent.com/923699/70169279-6ad48300-16c2-11ea-895c-3aec393ca9b6.png)

**Comment by thmspl** [comment]
Thank you for your fast response. After installing the `BCF` plugin and a restart of the program those two error messages appear:

![image](https://user-images.githubusercontent.com/8693771/70217824-2f799900-1742-11ea-803f-458e4cd324a2.png)

![image](https://user-images.githubusercontent.com/8693771/70217867-49b37700-1742-11ea-95c2-a47493688989.png)

**Comment by andyward** [comment]
For clarity, which BCF plugin are you using? (there are 2)

What version of Xplorer are you using? In the Help about

**Comment by thmspl** [comment]
I've installed the following plugin:

![image](https://user-images.githubusercontent.com/8693771/70221652-09a3c280-1749-11ea-8f93-8dbaf3fd27aa.png)

And I'm using the current version of the master branch.

**Comment by andyward** [comment]
There's been a breaking change between the v4 Xplorer and v5.x Xplorer that means v4 plugins won't work with the latest v5+ Xplorer viewer. We need to do some work so the plugin system is smart enough to handle this before updating the [official Xplorer release](http://docs.xbim.net/downloads/xbimxplorer.html). This needs some coordination with @CBenghi who maintains the v4 code and the Xplorer release

In the mean time, if you're up for DIY, I think you can build the v5 BCF plugin (in this repo) and manually deploy the plugin package. The plugins are a nuget package that gets unpacked with a manifest file in a Plugins folder under the bin.

**Comment by thmspl** [comment]
Thank you for your answers!

**Comment by CBenghi** [comment]
I'm reopening as a reminder of work to do on the plugin system

**Comment by andyward** [comment]
Hi Claudio,

What I was thinking is we need to roll out a 4.x Xplorer update that filters out incompatible plugins, and have this roll out before we push a 5.x release to the auto update (which I think is only something you can do).

An obviously we'd need the same check in v5 Xplorer. v5 Should also disable incompatible plugins until they're updated.

In terms of that check I guess we could do one of 

1. Quick and Dirty: Is the package version < Max version && > MinVersion (where min max are baked into Xplorer)
2. Proper Solution. Use the nuget dependency manifest to determine what's compatible with the 
runtime.

**Comment by CBenghi** [comment]
This has been taken care of now in the maintenance branch for v4 and in the develop branch for v5.1.
Can you confirm it is working for you, @andyward?

**Comment by andyward** [comment]
Yes, version 5.1.0.185 is working fine and picks up the v5 BCF plugin
