### ISSUE TITLE
[Question] What is the difference between OpeningsAndAdditionsIncluded and OpeningsAndAdditionsOnly

### ISSUE THREAD

**Issue by Noranius** [xBimTeam/XbimWindowsUI#138]
I'm on to implement the visualization of textures for `IfcSurfaceFeature`. I made it until loading the texture successfully. However, The method `GetShapeInstancesToRender` returns shapes with `XbimGeometryRepresentationType.OpeningsAndAdditionsIncluded` only. Whereas, `IfcSurfaceFeature` has `Xbim.Common.Geometry.XbimGeometryRepresentationType.OpeningsAndAdditionsOnly`. What would happen, if this is changed?

https://github.com/xBimTeam/XbimWindowsUI/blob/13bb09ab7543d23a6fee1892e60c250c374150d3/Xbim.Presentation/LayerStyling/SurfaceLayerStyler.cs#L212

**Comment by Noranius** [comment]
After some investigation I found that this is related to feature elements. I deactivated it. Currently there isn't any problem.

**Comment by bekraft** [comment]
There are geometry representations which consist of more than a single body. Additions are not widely used (only saw those in steel works). Openings or cuts can represent i.e. door recesses. As far I know this option controls the post geometry assembling phase (via boolean ops) - whether those features should affect the shown body or not. Deactivation will have impacts on the final representative geometry.
