### ISSUE TITLE
Color of BIM elements

### ISSUE THREAD

**Issue by minhnguyenlinknode** [xBimTeam/XbimWindowsUI#14]
Hi,

When I view IFC file using BimXplorer, I can see it renders various color for all elements (ex roof, windows, trees...). The question is does that color come from IFC file or it is defined by some algorithm?

Thanks,

**Comment by azura-vergo** [comment]
I think color has already defined in IFC file.
you can get the property "Color" of each element from IFC file.
wish may help you.

**Comment by CBenghi** [comment]
Hello,
the style of the elements is normally determined inside the ifc files, they are saved in the xbim file associated with geometry representations.

In case styles are defined you can find them in 3dmodelcontext, through the SurfaceStyles() function.

I think to remember that, if styling information is not present, then default styles per type are defined in a class called XbimColourMap (in Geometry).

It's possible for you to define completely arbitrary code to define the appearance of elements by implementing a custom layerStyler in WindowsUI.
There are a couple of examples on how to do this; if you are using the latest version of xbim then have a look at SurfaceLayerStyler and AlternateColourStyler under LayerStylingV2 folder of Xbim.Presentation.

What is it that you want to achieve?

**Comment by minhnguyenlinknode** [comment]
Thanks everyone. I understand it now. The thing I want to achieve is to use XBimQuery to extract the sub elements from the IFC file to produce another smaller IFC file. I can query the elements but is there a convenient way to create a new IFC file from those extracted elements?

**Comment by CBenghi** [comment]
I think @martin1cerny has worked on something to extract portions of an ifc file retaining its integrity, but I'm not sure. I think this uses a proper semantic model of the building.
I've got another implementation of such thing as an (hidden) part of XbimXplorer; have a look at IfcSimplify.xaml
A word of warning: it's a rough implementation just based on the text files, but it does get some work done in most scenarios.
BTW, i'm not sure how this relates to the original question on the style.

**Comment by martin1cerny** [comment]
@CBenghi is right, I work on this for the next release of XbimEssentials. It is a new `model.InsertCopy()` function which can be used to create submodels exactly as @minhnguyenlinknode described. It is in develop branch of XbimEssentials now. It will take some time until it gets published in master branch as it is the new generation of xBIM with loads of improvements and extensions (like IFC4 full support). But if you need this function now you can grab it from the [source](https://github.com/xBimTeam/XbimEssentials/blob/develop/Xbim.IO/Memory/MemoryModel.cs#L604) as it should also work with some minor enhancements for your current model. But be careful and test it well.

**Comment by minhnguyenlinknode** [comment]
Hi @martin1cerny. Can you give me quick example how to use model.InsertCopy() to create submodel?
For example, I have created function like this to query the model and return list of IPersistIfcEntity objects:            
            var parser = new XbimQueryParser(_model);
            var parseOk = parser.Parse(query);
            if (parseOk)
            {
                    var entities = parser.Results.LastEntities.ToList();
            }       
         
Then I want to create IFC file from these extracted entities.

So how can I use your new function model.InsertCopy(...) to suit my needs? 
At the moment I can write my own function but it is missing IFC style color elements.
