### ISSUE TITLE
multi selection and highlight selected objects

### ISSUE THREAD

**Issue by oiurew** [xBimTeam/XbimWindowsUI#142]
I'm try to use XbimWindowsUI to build winform viewer.
Is it possible to multi selection and highlight selected elements with using WinformsAccessibleControl and how to do it? 

https://github.com/xBimTeam/XbimWindowsUI/blob/13bb09ab7543d23a6fee1892e60c250c374150d3/Xbim.WinformsSample/FormExample.cs#L92

**Comment by andyward** [comment]
I've not tried this in the Winforms example, but the underlying WPF control supports multi-selection.

If you Ctrl-click in Xplorer it multi-selects.

**Comment by oiurew** [comment]
Thank you,andyward.
But what I want to do is multi-select through codebehind and I can't find any solution or similar question :'(

**Comment by andyward** [comment]
This is how it's implemented in the control: https://github.com/xBimTeam/XbimWindowsUI/blob/13bb09ab7543d23a6fee1892e60c250c374150d3/Xbim.Presentation/DrawingControl3D.xaml.cs#L544

i.e. there are various Selection modes. It defaults to `XbimMouseClickActions.Single` which clears the selection on every click.  If you change it (through`IfcMetaDataControl`) to Add or Toggle it should support multi selection.

**Comment by CBenghi** [comment]
Hi @oiurew,

I've pushed a change to develop that adds a button showing what to do.
There was an issue in the component that might have caused you problems in your tests.

Load a model with walls and see the code to select all the walls in 
https://github.com/xBimTeam/XbimWindowsUI/commit/f32cfda992d8e9c38a072a8fca3ed96ce3642fe2

Best,
Claudio

**Comment by oiurew** [comment]
Hi Andy,
I'll try it.Thanks for replying soon.You do help me a lot.

Hi Claudio,
Thank you for that update,that is exactly what I want!!

I'm so grateful for your help. :heart_decoration:
