### ISSUE TITLE
EntityWhereClauses on IfcObject.UniquePropertySetNames incorrectly implemented?

### ISSUE THREAD

**Issue by Moult** [xBimTeam/XbimWindowsUI#145]
I have a file which I cannot share, which has validation output such as:

> Entity #429 (IfcSpace) has validation failures.
> 	Issue of type EntityWhereClauses on IfcObject.UniquePropertySetNames.

Manually checking the pset names shows that they are all, indeed, unique. I am not sure why this error pops up.

**Comment by bekraft** [comment]
Hi! Seems that the implementation of the entity where clause was incorrect. It took the name of the relation - not of the property set.

**Comment by Moult** [comment]
Fantastic! Thanks for all your work!

**Comment by lukasz-sebastian-lupa** [comment]
I have encountered the same error with IfcBuilding (on ver. 5.1.297)
