### ISSUE TITLE
How to select an IFCSpace in the 3D viewer part ? 

### ISSUE THREAD

**Issue by Pedrodeo** [xBimTeam/XbimWindowsUI#147]
Hello,

I'm using the ifc file you deliver as an example (SampleHouse4.ifc) and I would like to know if it's possible to select an IFCSpace directly from the viewer, like it's possible to do in the treeview ( ex : Living Room, Bedroom, etc...)

Thank you

**Comment by CBenghi** [comment]
Hi,

select Styler configuration from the menu

![image](https://user-images.githubusercontent.com/5476273/80366721-03de8300-888a-11ea-958a-4a45fb0ba054.png)


Then enable the spaces:

![image](https://user-images.githubusercontent.com/5476273/80366681-f3c6a380-8889-11ea-86bf-639ee1b5f351.png)


If the spaces are entirely enclosed it might be tricky to select them with the mouse, but you can achieve that by clipping the model.

**Comment by Pedrodeo** [comment]
Thank you for your answer.
