### ISSUE TITLE
Cloning  XbimWindowsUI error in Visual Studio

### ISSUE THREAD

**Issue by joselaks** [xBimTeam/XbimWindowsUI#149]
I am trying to install XbimWindowsUIon my computer to be able to compile it, and when I try to clone it.
I get the attached error messages. I have all the framework packages installed (4.6., 4.61 and 4.7) but I can't. 
How can I correctly install explorer on my computer with Visual Studio 2019?
Best Regards,
José

![errorF](https://user-images.githubusercontent.com/8004858/82074296-efcfb980-96b0-11ea-9f23-9bf0c1817ad3.png)
![errorf2](https://user-images.githubusercontent.com/8004858/82074302-f2321380-96b0-11ea-895a-775cc9dc4987.png)
![error3](https://user-images.githubusercontent.com/8004858/82074312-f4946d80-96b0-11ea-8205-baae0aaa6b84.png)

**Comment by andyward** [comment]
Hi Jose,

My Portuguese is not so good(!), but it looks like you're missing the .net 4.7 SDK. You may just have the **runtime** installed but you need the **developer** version to build. Check in the Visual Studio installer that you have the development tools installed:

![image](https://user-images.githubusercontent.com/923699/82205958-49c5be80-98ff-11ea-86dd-e5f6fd3a37ca.png)

.. and checking 4.7 will install it for you.

You could also get the .net 4.7 Developer pack from https://dotnet.microsoft.com/download/dotnet-framework/net47

**Comment by joselaks** [comment]
Thanks Andy! It worked perfectly!
