### ISSUE TITLE
Wall to high

### ISSUE THREAD

**Issue by BjDi** [xBimTeam/XbimWindowsUI#15]
Hello, I started to use the XBim Viewer and I got a customer IFC file, where the XBim Explorere (Viewer)
displays one wall to high. Besides the windows are not transparent.
Surprisingly when I load the same file in my Application which uses the same Xbim.Presentation.dll,
the wall is ok and the windows are transparent.

With some other files the walls are too high as well but they are not if I open them in the Solibri Viewer

I could send you the files. Would you please send me an upload link (customer files) or should I send you a download link?

Your framework is realy great!!!!
[Walls2High.docx](https://github.com/xBimTeam/XbimWindowsUI/files/59468/Walls2High.docx)

**Comment by CBenghi** [comment]
Hello,
that's very odd. Please send me a link for dowload at claudio.benghi@gmail.com.
I'll investigate.
Best,
Claudio

**Comment by CBenghi** [comment]
Hello, I'm not sure what went wrong with your model, but in my case using xplorer I've not had the problem that you point to.
![image](https://cloud.githubusercontent.com/assets/5476273/11932934/bd9df002-a7f0-11e5-90df-a875eb61c576.png)

This ArchiCAD file has a number of warnings associated to it; lately ArchiCAD has relaxed their approach to geometries and we are constantly updating the Geometry engine in response to it.
Best,
Claudio

**Comment by CBenghi** [comment]
Hello @BjDi ,
I've made some progress on this issue and the one associated with the other file you sent. 
I'm running some tests now and In a couple of days I should be able to post a complete fix.
Best,
Claudio

**Comment by CBenghi** [comment]
@BjDi,
I've published a bugfix branch with some fixes, if you are in a rush you can get it from 
xBimTeam/XbimGeometry@b2811e216bcf1181c09fca60e4bec73c57f8dda0 
Best,
Claudio

**Comment by BjDi** [comment]
Hello Claudio,
I owe you my respect.
Thank you very much for your work.

I tried to get it run, but I got an error message.
[image: Inline-Bild 1]
I just compiled the dll's, copied them to the debug folder and directly
started the executable.

I have 2 or 3 other files with a similar behaviour, so I was courious if
they are fixed, too.
But anyway I'm not in a hurry and can wait for the merge (master).

(I compiled with VS2015, could that be the problem?)

Thank you once again.

Best,
Björn

2015-12-31 14:04 GMT+01:00 Claudio Benghi <notifications@github.com>:

**Comment by CBenghi** [comment]
As far as I know you can compile with VS2015, but do not update the toolkit to vs2015; continue using the c++ toolkit of vs2013 (visual studio asks you to update... resist the urge to press yes).
Otherwise I'm not sure why this did not work for you.
What I did to test was to compile geometry, make a new nuget package locally and update the package in windowsUI from a local folder.
That should work for you.
Best,
Claudio

**Comment by BjDi** [comment]
Hello Claudio,

thank you for your response.
It has been like you mentioned. I used the new toolkit (VS2015), which uses
a newer RunTime.
I will try it again with using the original as soon as possible.
(Using a local nuget package was a good tip for me, too)

Thank you very much.
Best,
Björn


2016-01-05 11:21 GMT+01:00 Claudio Benghi <notifications@github.com>:
