### ISSUE TITLE
Is it possible to write a command to select by global id?

### ISSUE THREAD

**Issue by Moult** [xBimTeam/XbimWindowsUI#158]
In the XBim Xplorer command window, I can type in: `select #90018` to select the entity with STEP ID 90018. Is it possible to do the same, but for a global ID instead?

**Comment by CBenghi** [comment]
Hello, I've patched the develop branch to add this to the command line.
See https://github.com/xBimTeam/XbimWindowsUI/commit/5a1e5a2eb084d9f249e0e65c7a2cc191187b7f32 and previous.

The whole command parsing needs revising but this should work.
