### ISSUE TITLE
How to add a new IIfcRelContainedInSpatialStructure relationship in a ifc file.

### ISSUE THREAD

**Issue by Ferbeas** [xBimTeam/XbimWindowsUI#165]
Hello,

I want to create the relationship between an IfcSpace and an IfcBuidingElementProxy. According to [this](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/schema/ifcproductextension/lexical/ifcspace.htm) the IfcSpace connects with an IfcProduct through the IIfcRelContainedInSpatialStructure relationship.

```
using (var model = IfcStore.Open(sample))
            {
                var theElement = model.Instances.FirstOrDefault<IIfcBuildingElementProxy>();
                var theSpace = model.Instances.FirstOrDefault<IIfcSpace>();
                //open transaction for changes
                using (var txn = model.BeginTransaction("AddRelationship"))
                {

                    var rel = model.Instances.New<IIfcRelContainedInSpatialStructure>(r =>
                    {

                        r.GlobalId = Guid.NewGuid();
                        r.RelatedElements.Add(theElement);
                        r.RelatingStructure = theSpace;
                    });
                    txn.Commit();
                }
                model.SaveAs("sample2.ifc");
            }
```
This is the error it gives
![image](https://user-images.githubusercontent.com/66945837/101350560-d1711b80-3897-11eb-85cf-7bd748f7488d.png)

How to properly use the IIfcRelContainedInSpatialStructure relationship?

**Comment by andyward** [comment]
When you create a new instance of a model entity it needs to be a class not an interface. `IIfcRelContainedInSpatialStructure` is an interface. Take the initial 'I' off and import the correct namespace (depending on whether you want IFC2x3 or Ifc4)

**Comment by Ferbeas** [comment]
Thanks @andyward, problem solved.
