### ISSUE TITLE
ModelOpacity with LayerStylingV2?

### ISSUE THREAD

**Issue by BjDi** [xBimTeam/XbimWindowsUI#17]
Hello,
to get a transparent model, I changed to the old Layerstyling and activated 
"SetOpacityPersent(m3d.Material, ModelOpacity); in 
DrawingControl3D.xaml.cs/AddLayerToDrawingControl(...)
which was uncommented.
That looks fine.
But how do I have to do it with the new LayerStylingV2 ?
Could you please help me?
Thank you in advance.

**Comment by CBenghi** [comment]
I'll look into this between Xmas and New year.

**Comment by BjDi** [comment]
Hello Claudio,
I tried to solve the problem and changed the 
Xbim.Presentation.WpfMaterial CreateMaterial(XbimTexture texture) Method.
There I always change color.Alpha to 0.25.
That works for the first run, but I could not see all furnitures through walls, only some.
Is that possible?
(This also happend with the old layerstyling)

**Comment by CBenghi** [comment]
There might be a sorting issue that affects rendering of transparent items in WPF.
I think that's out of our control at the moment.
We are working on a more accurate viewer component that will be using OpenGL and improve substantially the rendering capabilities... we are looking into somebody willing to fund its development.
Would your company be interested?

**Comment by CBenghi** [comment]
Just to note that we are not going to invest much more in the WPF viewer as the plans are to transition to a more powerful visual engine as soon as we have resources to invest.
