### ISSUE TITLE
Hiding single IPersistIfcEntity?

### ISSUE THREAD

**Issue by BjDi** [xBimTeam/XbimWindowsUI#18]
Hello,
can anybody tell me how to hide a single IPersistIfcEntity?
Do I have to write a new class that inherits from ILayerStylerV2?

**Comment by BjDi** [comment]
Now I have seen, this question was yet asked.

**Comment by CBenghi** [comment]
Hello, 
Sorry for the delay, have been cut off the internet for a few days... 
Your idea is correct; let me know if you manage to achieve it.
Claudio

**Comment by BjDi** [comment]
Hello Claudio,
thank you for your quick response. I hope I can try it in January.
Thank you for your help, too.
At the moment I would appreciate your opinion about one other open issue
("Walls to high").
That happens with other customers files, too. Is it a bug in the ifc files?
Could it be displayed 'correct' nevertheless?
I think, this could be an important point for my chief to make his desicion
to take or not to take
the viewer.
Thank you in advance.
Merry Christmas and a happy new year :-)
Björn

2015-12-16 14:19 GMT+01:00 Claudio Benghi <notifications@github.com>:
