### ISSUE TITLE
Not able to compile by using visual studio 2022

### ISSUE THREAD

**Issue by limweebeng** [xBimTeam/XbimWindowsUI#183]
I try to compile the source code by using visual studio. However, i have compilation error as shown below.
![Capture](https://user-images.githubusercontent.com/20635931/161412842-7314c197-0840-4c63-aa5a-691feffc1756.JPG)

**Comment by arfname** [comment]
I have the same problem.

**Comment by andyward** [comment]
Just tested out VS 2022 (17.1.4) and could reproduce the issue. For some reason the BCF project is not in the newer SDK csproj format, and it looks like 22 can't handle the fact that the xbim myget dependencies have been archived.

I've updated to latest Myget essentials and it that seemed to fix things

**Comment by andyward** [comment]
Fixed in Master and develop
