### ISSUE TITLE
Extract sub model and write to IFC

### ISSUE THREAD

**Issue by minhnguyenlinknode** [xBimTeam/XbimWindowsUI#19]
Hi @martin1cerny. Could you please give me an example code how to use [model.InsertCopy()](https://github.com/xBimTeam/XbimEssentials/blob/develop/Xbim.IO/Memory/MemoryModel.cs#L604) to create submodel?
For example, I have created function like this to query the model and return list of **IPersistIfcEntity** objects:

```csharp
var parser = new XbimQueryParser(_model);
var parseOk = parser.Parse(query);
if (parseOk)
{
    var entities = parser.Results.LastEntities.ToList();
}
```
Then I want to create IFC file from these extracted entities.

So how can I use your new function model.InsertCopy(...) to suit my needs?
At the moment I can write my own function but it is missing IFC style color elements.

Thanks.

**Comment by martin1cerny** [comment]
`InsertCopy()` function is [documented](https://github.com/xBimTeam/XbimEssentials/blob/develop/Xbim.IO/Memory/MemoryModel.cs#L586). You need to create new model and insert your objects in there. `mappings` is a dictionary which makes sure objects are not inserted multiple times so you should use one mapping dictionary per model. Other parameters allow you to define how you want to insert the copy of the object. It is important to understand structure of IFC to be able to bring over all objects you want and to leave out all you don't want. Allowing inverses seems to be simple solution but it tends to bring over almost entire model if you are not careful as IFC is not a hierarchical structure. Your best option is to use `PropertyTranformDelegate propTransform` parameter to define delegate which will filter properties of objects you pass to the function. You might easily end up with one or more include lists and one or more exclude lists of objects depending on what kind of context you want to bring over alongside with the products.
