### ISSUE TITLE
Feature request -> hide and unhide in the 3D view

### ISSUE THREAD

**Issue by Martin15135215** [xBimTeam/XbimWindowsUI#190]
Hi all

It would be nice to have a option to hide objects and unhide them :)

**Comment by andyward** [comment]
That's already implemented using `DrawingControl3D.HiddenInstances`. See 
https://github.com/xBimTeam/XbimWindowsUI/blob/faa8e9450866f929c7514e2b4b18d285648ccf75/XbimXplorer/XplorerMainWindow.xaml.cs#L1085
