### ISSUE TITLE
Is IfcSurfaceCurveSweptAreaSolid supported?

### ISSUE THREAD

**Issue by Jero9999** [xBimTeam/XbimWindowsUI#20]
When I try and view the attached file I get all of the expected geometry except the 'M'. It is created using an IfcSurfaceCurveSweptAreaSolid. The only thing it shows is a flat representation of the profile that is meant to be swept.
[BIM Logo.zip](https://github.com/xBimTeam/XbimWindowsUI/files/96843/BIM.Logo.zip)

**Comment by CBenghi** [comment]
Hi,
we are extending the geometry implementation with IFC4. 
I'll look into the issue in the coming days.
Best,
Claudio

**Comment by CBenghi** [comment]
Yay!!!
It's all there!
:)

![image](https://cloud.githubusercontent.com/assets/5476273/19663977/7adf69d8-9a36-11e6-9258-957085adfeb2.png)
