### ISSUE TITLE
WPF which has the DrawingControl3D element can't load in the Revit

### ISSUE THREAD

**Issue by AHSss** [xBimTeam/XbimWindowsUI#200]
When I used the RevitAPI to load the wpf-window which has the DrawingControl3D element,it was show me the "System.MissingMethodException“,such like this:
![image](https://user-images.githubusercontent.com/120151868/220152545-561adf3f-b2fc-4dc6-b0a1-62acfb6473fe.png)
Without the Revit,the wpf-window which has the DrawingControl3D element can normal operate.But I hope load it in the Revit.
How can I open the  DrawingControl3D in Revit？Please show me the way.Thanks very much!

**Comment by andyward** [comment]
So what it looks like is that there's a version of HelixToolkit running in Revit that's not compatible with the version that Xbim.Presentation is expecting. 

What may be happening is another Revit addin is providing an incompatible version of HelixToolkit (or possibly a downstream dependency). Bear in mind with a Revit plugin you are sharing the same application domain with Revit and any other Addin code.

Does the viewer work at all? it's not immediately clear if this is failing during interaction with the model, or just when the Drawing3DControl is initialising.

Try setting DrawingControl3D.SelectionHighlightMode to `SelectionHighlightModes.WholeMesh`

If no luck, you'll have to provide some more details ideally a repo with some code.

**Comment by AHSss** [comment]
@andyward 
I had try to use the version 2.14.0.0 of HelixToolkit.Wpf which is in the Xbim.WindowsUI's Nuget packages to create an element in my xaml-file,it can normal start in the Revit.But I used the Xbim.Presentation's DrawingControl3D which both have the same version of HelixToolkit.Wpf to create an element in my xaml-file,it at once can't start in the Revit and show me the  "System.MissingMethodException:can't find Void HelixToolkit.Wpf.MeshBuilder.AddTube.....“.Here is my code and the screenshot.Could you please help me to solve this problem. 
![1676975737541](https://user-images.githubusercontent.com/120151868/220321706-9a0918eb-ad27-4907-8185-2c97bd6efea7.png)
![1676975984478](https://user-images.githubusercontent.com/120151868/220322593-721a9847-5017-4c8f-aa9e-39ec742507bd.png)
![1676976090432](https://user-images.githubusercontent.com/120151868/220323006-45458684-afcf-43c9-9c20-4480f8d4bb3d.png)
[WPF4Xbim.zip](https://github.com/xBimTeam/XbimWindowsUI/files/10792638/WPF4Xbim.zip)

**Comment by andyward** [comment]
Really hard to say without the full revit Addin code and especially the code you're using for Xbim.Presentation. You shouldn't need to include HelixToolkit yourself - Xbim.Presentation brings it in for you.

Why don't you use the new style SDK csproj format? - it's a lot simpler to see dependencies. I created a fork at https://github.com/andyward/WPF4Xbim 

See [equivalent Sdk csproj](https://github.com/andyward/WPF4Xbim/blob/main/Wpf4Xbim.Sdk/Wpf4Xbim.Sdk.csproj)

Here's Helix and the Xbim DrawingControl3D running side by side with the Revit assemblies

<img width="362" alt="image" src="https://user-images.githubusercontent.com/923699/220338243-643252ce-d27b-4c8c-8082-e383d85c1a75.png">

**Comment by AHSss** [comment]
@andyward 
I had try to open the https://github.com/andyward/WPF4Xbim，but can't to see the page‘s context.Is there some problem with me?
![image](https://user-images.githubusercontent.com/120151868/220353079-50bc80dd-8385-4dd7-a2c4-a82021f8ce37.png)

**Comment by andyward** [comment]
Sorry, I'd not made it public. Try now.

**Comment by AHSss** [comment]
@andyward 
Thank you very much for help me to solve this problem ! I had try your fork . It can  running side by side with the Revit . But I really want it running inside the Revit Add-in Manager . In my code , I had write the method for it running in the Revit .
![image](https://user-images.githubusercontent.com/120151868/220386763-3458cef8-b865-4c06-a644-63635e0f55ba.png)
But When I was try it , only can running the Helix one , if there has Xbim DrawingControl3D , the Revit  will show me the error . 
I know the Xbim.Presentation include Helix , why Helix can work right , but  DrawingControl3D is not ? In the errorMassage , It ponited the function-HelixToolkit.Wpf.MeshBuilder.AddTube is not found .It's the problem? Is there a way to solve it ? I just want XbimWindowUI can running in the Revit ! Anyway , thank you again for your hlep !

**Comment by andyward** [comment]
Sorry can't really help unless you can provide a repro I can look at (no zip files please). 

I've just tested opening Xbim.WindowsUI 5.1.228 in a Revit 2023 plugin and all is fine. 

I see you're in Revit 2019 - Have you tried other Revit versions?

Other suggestions:
* Check what versions of assemblies are loaded in the Revit application (Debug -> Windows -> Modules)

e.g. note I have 2.17.0 running. It seems that Dynamo for Revit also ships a version of HelixToolkit.WPF
<img width="987" alt="image" src="https://user-images.githubusercontent.com/923699/220705184-0dd80db4-e0f7-4d95-aa7d-0c9624546be9.png">

* Try disabling all other addins in Revit and restesting

If there's a collision it's possible you can use a Custom Assembly Resolver to ensure the correct version is loaded in. See https://forums.autodesk.com/t5/revit-api-forum/proper-way-to-handle-app-config-bindingredirects-in-revit-add-in/td-p/5692149

**Comment by AHSss** [comment]
@andyward 
Hi Andy,
Thank you very much ! I have solved this problem . As you said , There was a too old version of HelixToolkit in my Dynamo for Revit .  I covered it with the HelixToolkit.Wpf.dll which is in Nuget packages . Finally it can be work OK ! Thanks! You do hlep me a lot .
<img width="813" alt="image" src="https://user-images.githubusercontent.com/120151868/221388820-3cdb761e-9d55-4f09-b140-1cf8af7d8989.png">
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/120151868/221388836-9058e82c-13d3-43f0-87f1-3bd4d594ecce.png">
