### ISSUE TITLE
*.ifc vs. *.ifcXml - Different wall mesh displayed 

### ISSUE THREAD

**Issue by leobroom** [xBimTeam/XbimWindowsUI#206]
Hey folks,

When I am saving the same file of an created ifc file as an ifc and an ifcXML, the ifcXML version shows me some meshing errors.

The IfcIndexedPolyCurve looks fine for me:

`<SweptArea id="i41" xsi:type="IfcArbitraryClosedProfileDef" ProfileType="area" ProfileName="dummy">`<br>`
                                <OuterCurve id="i39" xsi:type="IfcIndexedPolyCurve">`<br>`
                                  <Points id="i40" xsi:type="IfcCartesianPointList2D">`<br>`
                                    <CoordList>`<br>`
                                      <IfcLengthMeasure-wrapper pos="0 0">0</IfcLengthMeasure-wrapper>`<br>`
                                      <IfcLengthMeasure-wrapper pos="0 1">0</IfcLengthMeasure-wrapper>`<br>`
                                      <IfcLengthMeasure-wrapper pos="1 0">1000</IfcLengthMeasure-wrapper>`<br>`
                                      <IfcLengthMeasure-wrapper pos="1 1">0</IfcLengthMeasure-wrapper>`<br>`
                                      <IfcLengthMeasure-wrapper pos="2 0">1000</IfcLengthMeasure-wrapper>`<br>`
                                      <IfcLengthMeasure-wrapper pos="2 1">360</IfcLengthMeasure-wrapper>`<br>`
                                      <IfcLengthMeasure-wrapper pos="3 0">0</IfcLengthMeasure-wrapper>`<br>`
                                      <IfcLengthMeasure-wrapper pos="3 1">360</IfcLengthMeasure-wrapper>`<br>`
                                    </CoordList>`<br>`
                                  </Points>`<br>`
                                  <Segments>`<br>`
                                    <IfcLineIndex-wrapper pos="0">1 2 3 4 1</IfcLineIndex-wrapper>`<br>`
                                  </Segments>`<br>`
                                </OuterCurve>`<br>`
                              </SweptArea>``<br>`

Any Ideas, what went wrong?

Greetings.

![xBimIfcIndexedPolyCurveError](https://github.com/xBimTeam/XbimWindowsUI/assets/7702475/151ecbd2-829c-4f62-839a-08c419470989)

[errorWall.zip](https://github.com/xBimTeam/XbimWindowsUI/files/12181033/errorWall.zip)

**Comment by andyward** [comment]
I haven't dug into it but it looks like we've fixed this in v6. i.e. the validation warning is no longer occurring and we're tesselating the ifcxml fine.

<img width="1557" alt="image" src="https://github.com/xBimTeam/XbimWindowsUI/assets/923699/9a77d9aa-3365-4197-9f43-7780adff57e2">

i.e. these validation warning may be incorrect in 5.1:

```
Entity #25 (IfcArbitraryClosedProfileDef) has validation failures.
	Issue of type EntityWhereClauses on IfcArbitraryClosedProfileDef.WR1.
Entity #33 (IfcShapeRepresentation) has validation failures.
	Issue of type EntityWhereClauses on IfcShapeRepresentation.CorrectItemsForType.

```

**Comment by andyward** [comment]
And the may be similar false negatives in the Step IFC:
<img width="1545" alt="image" src="https://github.com/xBimTeam/XbimWindowsUI/assets/923699/7fffa749-7ee1-4b71-b538-b4947e0f1e97">
(v6 on the right)

**Comment by leobroom** [comment]
Hey Andy, thank you for your answer! Looks good! I didnt realise, that I used an ancient version btw. (4.0)  I downloaded it a few days ago from here: https://docs.xbim.net/downloads/xbimxplorer.html. I didn¨t check the git repo, which i should have done. Maybe it makes sense to update the link. 

The Explorer is an amazing tool for analysing ifc data! 

Greetings,
Leon
