### ISSUE TITLE
About installshield

### ISSUE THREAD

**Issue by chasel-hu** [xBimTeam/XbimWindowsUI#21]
hi 
i using installshield to create setup file
there is an error when i try to open ifc file
![_20160125163429](https://cloud.githubusercontent.com/assets/8624914/12546077/4fa119fa-c382-11e5-91eb-6acefe54813f.png)

but i hava install vc++ 2013
![_20160125163451](https://cloud.githubusercontent.com/assets/8624914/12546093/69f824ec-c382-11e5-8b43-f37081317bf5.png)

can you get me some help?
thank you

**Comment by LloydPickering** [comment]
Is it possible something in Installshield is forcing it to use x86? That would mean it is looking for the x86 redistributables, not the x64 you have installed.

**Comment by CBenghi** [comment]
Hello, 
I'm closing this as we think that the latest master branch should work well.
If you still have problems, please reopen.
