### ISSUE TITLE
Elements not displayed after an IFC file is loaded

### ISSUE THREAD

**Issue by Proektsoft-EOOD** [xBimTeam/XbimWindowsUI#211]
Hi, I tried to load this file with Xbim Windows UI project, but the elements are not visible.
[taper.zip](https://github.com/xBimTeam/XbimGeometry/files/13487879/taper.zip)

It shows correctly in all other viewers I tried. Also, there is data in the IfcStore. It does not throw any exceptions. Am I missing something?

![image](https://github.com/xBimTeam/XbimWindowsUI/assets/90918363/f0f0b507-e31a-4191-810e-8a9840e47dd0)

**Comment by andyward** [comment]
What's the origin of the model? Seems to have lot of errors - e.g. it's IFC2x3 but contains IFC4 types. Placement and styling also look invalid.  I tried in Zoom and it fails to load there. BIMVision must be doing a lot of work to handle the invalid data.

Have you tested it in https://validate.buildingsmart.org/ ?

**Comment by Proektsoft-EOOD** [comment]
Hi, Andy!

Thank you! That was exactly the case. After verifying and removing all the issues, it worked. :)
