### ISSUE TITLE
ifc4-file not loading 

### ISSUE THREAD

**Issue by goldv72** [xBimTeam/XbimWindowsUI#218]
[TEST_IFC4.zip](https://github.com/user-attachments/files/16906619/TEST_IFC4.zip)
Hello! I can't load this file.
I have warnigs/errors like 'entity #3151 is referenced but could not instantiated'
could you help me

**Comment by andyward** [comment]
Have you tried running it through the IFC Validation service at https://www.buildingsmart.org/users/services/ifc-validation-service/ ?
I had a quick look and it appears that there's some syntax errors in most of the OCKS/KKS property values. There's what looks like Russian text in the properties, but the IFC encoding is incorrect on the Description attributes of many of the values. This looks like a fault in the Aveva exporter. If you had the original model maybe check if there's a version update for AVEVA.

Unfortunately xbim's parser is just dropping the whole entity and causing knock-on issues.

**Comment by goldv72** [comment]
thanks, didn't know about this service. there is indeed a bug.
i fixed them all. now everything is ok

**Comment by goldv72** [comment]
thanks, didn't know about this service. there is indeed a bug.
i fixed them all. now everything is ok

**Comment by goldv72** [comment]
close
