### ISSUE TITLE
Faulty display of boolean objects

### ISSUE THREAD

**Issue by gyorm** [xBimTeam/XbimWindowsUI#219]
I have discovered some inconsistency in the display of boolean objects. The problem is related to my older post on stackoverflow, when I thought the problem is in my code:

https://stackoverflow.com/questions/78792047/faulty-display-of-ifcbooleanclippingresult

however, as I went through the code of XbimXplorer, I ran a build from visual studio, and the exe I downloaded from the website simultaneously:

![image](https://github.com/user-attachments/assets/875bd450-402b-4e1f-8952-6ff7dd6e5e13)

The right one is the expecteed result, as the object is an INTERSECTION bool object. (see stackoverflow link)
And noticed that the earlier build (the installed exe) is displaying stuff as expected (such as BIMVision, and other applications), while the newest fresh build was faulty. This is consistent with the problems i'm describing in my stackoverflow post. 

Can someone help me out with this?

**Comment by andyward** [comment]
Any chance you can provide the model? It looks like a boolean regression in 5.1 but will need to investigate if we've already fixed it.

**Comment by gyorm** [comment]
Hi!

Of course I can:
[Ausmass.zip](https://github.com/user-attachments/files/16976170/Ausmass.zip)

**Comment by andyward** [comment]
Confirmed it's not working in 5.1.0742 but was OK in v4.
![image](https://github.com/user-attachments/assets/7343175f-03d5-48e5-8a21-62166cdc8b2b)

I can also say it's displaying OK in v6 (netcore branch of Geometry)

![image](https://github.com/user-attachments/assets/692cea90-6a36-4fe0-8dcf-7a891e222902)

So it appears v5.1 is ignoring the INTERSECTION Boolean method. But just spotted you  are using IfcBooleanClippingResult not IfcBooleanResult

[IfcBooleanClippingResult](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD1/HTML/link/ifcbooleanclippingresult.htm) is specialised to always do a DIFFERENCE operator. So the IFC is technically invalid.

Have you tried validating this model [here](https://www.buildingsmart.org/users/services/ifc-validation-service/)?

Switching the entity to `# 75=IFCBOOLEANRESULT(.INTERSECTION.,#53,#70);` fixed it for me in 5.1

**Comment by gyorm** [comment]
Indeed! I modified my code that generates the IFC to use BooleanResult instead, and now even my own Xbim based viewer displays it correctly.

![image](https://github.com/user-attachments/assets/9f943a51-b867-4fce-b695-c541ed455007)

Many thanks, I consider my issue solved.
I don't know wether the inconsistency between the versions are a problem, but what you kindly explained about the BooleanResult vs BooleanClippingResult makes sense.

**Comment by andyward** [comment]
Not sure if it was deliberate or not, but clearly 5.1 is being strict about the implementation, where 4 was relaxed - and we seem to be relaxed about it again in v6. I don't plan to revisit the 5.1 implementation given it's an edge case so will close
