### ISSUE TITLE
Chinese garbled question about XbimWindowsUI

### ISSUE THREAD

**Issue by hejiquan** [xBimTeam/XbimWindowsUI#22]
Default
![image](https://cloud.githubusercontent.com/assets/11800955/12547194/d840dbe0-c389-11e5-9222-d16d738d6b9f.png)

Add Code -> model.CodePageOverride = Encoding.GetEncoding("gb2312").WindowsCodePage;
![image](https://cloud.githubusercontent.com/assets/11800955/12547148/859430b8-c389-11e5-9c92-9cfe82f63dba.png)
![image](https://cloud.githubusercontent.com/assets/11800955/12547163/a6c2fb48-c389-11e5-9bff-e67f5cdf3460.png)

I hope to get your help.
Thanks

**Comment by CBenghi** [comment]
Hello,
there's not much we can do without the IFC file.
Can you send me a sample? Also I'd need to know what the text should say instead.
Maybe you can send the file to claudio.benghi@gmail.com
Best,
Claudio

**Comment by hejiquan** [comment]
Hello CBenghi,
Please check the attachment for your reference.
http://share.weiyun.com/573388dce4b0696535e7fd3d469d0f9d

**Comment by CBenghi** [comment]
Hello,
Sorry for the delay, I've been quite busy with updates for the IFC4 version.
I'm sorry but without the file there's not much I can do.
Please open the issue again if you can upload the ifc file.
Best
