### ISSUE TITLE
“How to Capture and Save an Isometric View of a 3D Model as a PNG File Using Xbim Libraries"

### ISSUE THREAD

**Issue by SergioSerran** [xBimTeam/XbimWindowsUI#221]
Is there a way to obtain an isometric view of my 3D model and save it as a PNG file? I am using the Xbim libraries to load and visualize IFC files in a WPF application. I need guidance on how to capture and save an isometric view of the model.

```csharp
// Xbim.Essentials 5.0.200
// Xbim.ModelGeometry.Scene 5.0.200
// Xbim.Presentation 5.0.200

using System.Windows;
using System.Windows.Data;
using Xbim.Ifc;
using Xbim.ModelGeometry.Scene;
using Xbim.Presentation;

namespace wpf2bim
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            Loaded += MainWindow_Loaded;
        }

        private void MainWindow_Loaded(object sender, RoutedEventArgs e)
        {
            ModelProvider?.Refresh();
            openFile();
        }

        private ObjectDataProvider ModelProvider
        {
            get
            {
                return FindResource("ModelProvider") as ObjectDataProvider;
            }
        }

        private void openFile()
        {
            var model = IfcStore.Open(@"C:\Users\Documents\Ruta\prisma.ifc");
            var context = new Xbim3DModelContext(model);
            context.CreateContext();

            if (ModelProvider != null)
            {
                ModelProvider.ObjectInstance = model;
            }
        }
    }
}
```
Expected behavior:
I expect to be able to capture an isometric view of the 3D model and save it as a PNG file.

Actual behavior or exception details:
Currently, I am unable to find a method to capture and save an isometric view of the model.

**Comment by andyward** [comment]
Moving this to xbim.WindowsUI as it's a WPF question

**Comment by andyward** [comment]
I'm not seeing how you're interacting with DrawingControl3D - that's the important piece, as it translates the tesselated geometry into a 2D representation you can take image of programatically.

The basic steps are:

1. Load the model into the DrawingControl3D - you seem to be doing (`ModelProvider.ObjectInstance = model` but I don't see any code to set `DrawingControl3D.Model`: [see here](https://github.com/xBimTeam/XbimWindowsUI/blob/faa8e9450866f929c7514e2b4b18d285648ccf75/Xbim.Presentation/DrawingControl3D.xaml.cs#L857))
   Confirm you can view the model on screen
2. Set the Camera mode to Orthographic (to get an isometric view): `DrawingControl.Viewport.Orthographic = true;`
3. Capture the image as a PNG: See this example in the [Bcf plugin](https://github.com/xBimTeam/XbimWindowsUI/blob/faa8e9450866f929c7514e2b4b18d285648ccf75/XplorerPlugin.Bcf/MainWindow.xaml.cs#L278)

Hope that helps

**Comment by SergioSerran** [comment]
Thank you very much, ANDYWARD. It worked correctly. I’m sharing the code:
using System;
using System.IO;
using System.Windows;
using System.Windows.Media.Imaging;
using Xbim.Ifc;
using Xbim.ModelGeometry.Scene;
using Xbim.Presentation;
using System.Windows.Media;
using System.Windows.Media.Media3D;

namespace IfcViewerWpf
{
    public partial class MainWindow : Window
    {
        private Xbim3DModelContext _modelContext;

        public MainWindow()
        {
            InitializeComponent();
            Loaded += MainWindow_Loaded; // Ejecuta cuando se carga la ventana
        }

        private void MainWindow_Loaded(object sender, RoutedEventArgs e)
        {
            // Cargar el modelo IFC
            LoadIfcFile();

            // Configurar la vista isométrica
            ConfigureViewer();

            // Capturar y guardar la imagen
            CaptureAndSaveSnapshot(@"C:\Users\Documents\Ruta\prisma.png");
        }

        private void LoadIfcFile()
        {
            // Cargar el archivo IFC
            var model = IfcStore.Open(@"C:\Users\Documents\Ruta\prisma.ifc");

            // Crear el contexto 3D para el modelo
            _modelContext = new Xbim3DModelContext(model);
            _modelContext.CreateContext();

            // Asignar el modelo al control de visualización 3D
            Viewer3D.Model = model;
        }

        private void ConfigureViewer()
        {
            // Configurar la cámara para vista isométrica
            //  Viewer3D.CameraProperties.Position = new Point3D(10, 10, 10); // Ajustar posición según sea necesario
            //Viewer3D.CameraProperties.LookAt(new Point3D(0, 0, 0)); // Centrar la cámara en el origen
            //Viewer3D.CameraProperties.UpDirection = new Vector3D(0, 0, 1); // Dirección "arriba" de la cámara

            // Configurar la cámara en modo ortográfico
             Viewer3D.Viewport.Orthographic = true;

        }

        private void CaptureAndSaveSnapshot(string outputPath)
        {
            // Capturar la imagen del control
            var snapshot = CaptureImage(Viewer3D);

            // Guardar la imagen en el archivo especificado
            SaveImage(snapshot, outputPath);
        }

        private BitmapImage CaptureImage(DrawingControl3D control)
        {
            // Renderizar el control en un RenderTargetBitmap
            var renderTarget = new RenderTargetBitmap(
                (int)control.ActualWidth,
                (int)control.ActualHeight,
                96, 96, PixelFormats.Pbgra32);

            renderTarget.Render(control);

            // Convertir el RenderTargetBitmap a BitmapImage
            var bitmapImage = new BitmapImage();
            var encoder = new PngBitmapEncoder();
            encoder.Frames.Add(BitmapFrame.Create(renderTarget));

            using (var stream = new MemoryStream())
            {
                encoder.Save(stream);
                stream.Seek(0, SeekOrigin.Begin);

                bitmapImage.BeginInit();
                bitmapImage.CacheOption = BitmapCacheOption.OnLoad;
                bitmapImage.StreamSource = stream;
                bitmapImage.EndInit();
            }
            return bitmapImage;
        }

        private void SaveImage(BitmapImage bitmapImage, string outputPath)
        {
            // Guardar la imagen como PNG
            var encoder = new PngBitmapEncoder();
            encoder.Frames.Add(BitmapFrame.Create(bitmapImage));

            using (var stream = new FileStream(outputPath, FileMode.Create))
            {
                encoder.Save(stream);
            }
        }
    }
}

Also: 

<Window x:Class="IfcViewerWpf.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:presentation="http://schemas.Xbim.com/Presentation"
        mc:Ignorable="d"
        Title="IFC Viewer" Height="600" Width="800">
    <Grid>
        <presentation:DrawingControl3D x:Name="Viewer3D" />
    </Grid>
</Window>

I would like to know if there is any property to manipulate the camera or if predefined views such as dimetric, trimetric, etc., already exist? I would also like to ask if there is a way to remove the grid from the PNG capture?

And finally, is there any way to add measurement dimensions and have them appear in the 3D model

![image](https://github.com/user-attachments/assets/fb966945-64bf-4d22-bf71-df991621c50d)
![prisma](https://github.com/user-attachments/assets/cd20d288-276d-4429-8470-d71c34763609)

**Comment by andyward** [comment]
You can definitely manipulate the camera - most of this is in HelixToolkit e.g. [CameraHelper.cs](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.Wpf.Shared/Helpers/CameraHelper.cs)

Take a look at the code [here](https://github.com/xBimTeam/XbimWindowsUI/blob/faa8e9450866f929c7514e2b4b18d285648ccf75/Xbim.Presentation/DrawingControl3D.xaml.cs#L1874) where we actually provide a full example creating a PNG image from the 3D scene, including removing the annotations like the grid, cube etc.

Re: measuring - there's a basic measuring capability built into the Windows UI Control. If you hold down 'Alt' while clicking points you'll see it in action:

![image](https://github.com/user-attachments/assets/91dc30d2-85b8-4838-b347-1343e6da3c90)

**Comment by SergioSerran** [comment]
I really appreciate your support, Andyward
