### ISSUE TITLE
Xbim.Presentation in wpf application

### ISSUE THREAD

**Issue by Maxima078** [xBimTeam/XbimWindowsUI#24]
Hi,

I'm looking for documentation or samples to help me during Xbim integration.
I'd like to be able to open ifc file and display it as part of a simple wpf application.

Thanks,

Max.

**Comment by bimbangboom** [comment]
If you grab the nuget package for the WindowsUI, it includes a sample
project that demonstrates an IFC explorer.

Andy

**Comment by Maxima078** [comment]
Thank you for your answer. 
I cannot see any sample included in the package folder and in my solution neither when the package is installed. Maybe you did'nt mean during installation but directly in source code ?

But I've found the control in XbimXplorer and I was able to load my ifc like this:
    
    <xbimcontrol:DrawingControl3D Grid.Row="1" Model="{Binding xModel}" />

Where xModel is XbimModel initialized like this:

    var xModeltemp = new XbimModel();
    var _temporaryXbimFileName = Path.GetTempFileName();
    xModeltemp.CreateFrom(ifcFilename, _temporaryXbimFileName, reportPDel, true);
    var context = new Xbim3DModelContext(xModeltemp);
    context.CreateContext(geomStorageType: XbimGeometryType.PolyhedronBinary, progDelegate: reportPDel, adjustWCS: false);
    
    xModel = xModeltemp;

It would be nice to have a usercontrol version of XbimXplorer but I can propably make it myself.
This framework is very usefull, do you know the next release date?

Thanks,

Max.

**Comment by bimbangboom** [comment]
Correct.  The nuget source package.

As you have surmised, DrawingControl3D is the xaml control for use in wpf.
There are a couple more controls that you will see once you grab the source
package and open the solution.

Andy

**Comment by Maxima078** [comment]
Thank you. I'll check that.
By the way I noticed a potential mistake here:
https://github.com/xBimTeam/XbimWindowsUI/blob/master/Xbim.Presentation/Xbim3DViewerControl.xaml.cs#L50
The dependency property is not attached to the correct type (DrawingControl3D instead of Xbim3DViewerControl, 4 occurences)

Max.
