### ISSUE TITLE
Entity Faces and Edges

### ISSUE THREAD

**Issue by miosepayo** [xBimTeam/XbimWindowsUI#25]
Hi,

I plan to retrieve faces and edges (not triangulated) for physical entity (Wall, Beam etc ...). I guess this is releated to XBimShapeInstance but after searched the code for couple of day but don't get the best to way to achieve this. Any help ?

Is this related to MeshGeometry3DExtensions read method ? Case command for faces is empty ...

Thanks for your work on this project.

**Comment by miosepayo** [comment]
Hello,

Any news/plans on this one ?

Best regards

**Comment by CBenghi** [comment]
This issue was moved to xBimTeam/XbimGeometry#28
