### ISSUE TITLE
Selection suggestion

### ISSUE THREAD

**Issue by theebow** [xBimTeam/XbimWindowsUI#27]
Hi the team
Have 2 suggestions to submit you in DrawingControl3D.xaml.cs :

1 - in the  "private static void OnSelectedEntityChanged(..." function
replace
            if (!d3D._selectedEntityChangeTriggedBySelectionChange)
by
            if (d3D.SelectionBehaviour != DrawingControl3D.SelectionBehaviours.MultipleSelection)

then we can add more than one entity to the selection collection

2 - Turn the "protected ObservableMeshVisual3D Highlighted;" on Public
then we can control the selection zoom on like this :
                    Rect3D r3D = drawingControl3D1.Highlighted.Mesh.GetBounds();

```
                drawingControl3D1.ZoomTo(new XbimRect3D(new XbimPoint3D(r3D.X, r3D.Y, r3D.Z),
                                                        new XbimVector3D(r3D.SizeX, r3D.SizeY, r3D.SizeZ)));
```

i don't want to do the commit myself, don't understand anything on github for the moment :)

**Comment by SteveLockley** [comment]
Hi Theebow we are looking at this just now, thanls

**Comment by theebow** [comment]
For information : (CtrlGrid is a Datagridview and CtrlViewer3D is a DrawingControl3D)
thank you to pay attention to this code comments ;)

```
// viewer selection update
for (int i = 0; i < CtrlGrid.SelectedRows.Count; i++)
 {
         ObjElec objToSelect = CtrlGrid.SelectedRows[i].Tag as ObjElec;
         IPersistEntity ent = IfcStore.Instances[int.Parse(objToSelect.Label)];

         // both two lines are (very) important, just any one of the 2 not working
         CtrlViewer3D.Selection.Add(ent);
         CtrlViewer3D.SelectedEntity = ent;
 }

 CtrlViewer3D.ZoomSelected();  // out of work because Highlighted.mesh == null
```

`

**Comment by theebow** [comment]
oups sorry i forgot something : if you want to be able to select entity from outside de DrawingControl3D
like i do, you have to (little) update DrawingControl3D.xaml.cs : 
go to
 `private static void OnSelectedEntityChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)`

and change 
`if (!d3D._selectedEntityChangeTriggedBySelectionChange)`
by
`if (!d3D._selectedEntityChangeTriggedBySelectionChange && d3D.SelectionBehaviour != DrawingControl3D.SelectionBehaviours.MultipleSelection)`

**Comment by CBenghi** [comment]
Hello,
regarding your point 1: to add more than one entity to the selection collection you should use the `Selection` property of the control. That seems to work for me.
```csharp
var s = new EntitySelection();
foreach (var item in ElementsToSelect)
{
	s.Add(Model.Instances[item]);
}
window.DrawingControl.Selection = s;
```

2 - we have a public ZoomSelected(); function for you in the control
:)

Happy to close this issue?

**Comment by CBenghi** [comment]
Hello,
regarding your point 1: to add more than one entity to the selection collection you should use the `Selection` property of the control. That seems to work for me.
```csharp
var s = new EntitySelection();
foreach (var item in ElementsToSelect)
{
	s.Add(Model.Instances[item]);
}
window.DrawingControl.Selection = s;
```

2 - we have a public ZoomSelected(); function for you in the control
:)

Happy to close this issue?

**Comment by CBenghi** [comment]
Hello,
regarding your point 1: to add more than one entity to the selection collection you should use the `Selection` property of the control. That seems to work for me.
```csharp
var s = new EntitySelection();
foreach (var item in ElementsToSelect)
{
	s.Add(Model.Instances[item]);
}
window.DrawingControl.Selection = s;
```

2 - we have a public ZoomSelected(); function for you in the control
:)

Happy to close this issue?

**Comment by theebow** [comment]
ok i understood : there is no "reactor" on Selection.Add, it is on the set value Selection property, this is why i had to call the SelectedEntity one
i'm so stupid :)
