### ISSUE TITLE
Tearing in geometry for IfcExtrudedAreaSolid

### ISSUE THREAD

**Issue by Jero9999** [xBimTeam/XbimWindowsUI#28]
I am coming across examples of tearing in the geometry for extruded area solids (though it might be for other things too)
First example: Looking at the end of an extruded solid. See the edges tearing. Note: the profile here is a composite curve.
![image](https://cloud.githubusercontent.com/assets/4205884/17655678/4312816a-6305-11e6-8b99-33537b35da14.png)

Second example: This is slightly different in that it is not the end tearing away from the 'extrusion' but the different parts of the extrusion itself
![image](https://cloud.githubusercontent.com/assets/4205884/17655704/886b6880-6305-11e6-80fe-463ef3dc668b.png)
Note: the profile here is a simple polyline and doesn't seem to have a problem. The extrusion here is actually a revolved area solid

Here is the IFC file for the first example
[CurvedFaceTests.Ifc.txt](https://github.com/xBimTeam/XbimWindowsUI/files/417532/CurvedFaceTests.Ifc.txt)

Version note:
my version of xbim xplorer reports it is 3.2.1.0.
File version: 3.2.1601.19255

**Comment by CBenghi** [comment]
Hello,
we've published a new version of the Geometry engine, and we're back at evaluating odd behaviours.
It would be nice if you could also send the second sample.
Thanks,
Claudio

**Comment by CBenghi** [comment]
This issue was moved to xBimTeam/XbimGeometry#29
