### ISSUE TITLE
Open a large models

### ISSUE THREAD

**Issue by kozintsev** [xBimTeam/XbimWindowsUI#31]
Hello!

You have tested the program for work with large models?
During the visualization occurs some simplification and optimization?
I can send a few models for testing. On my computer, these models can not be opened in XbimXplorer but they open in Solibri Model Viewer.

Regards, Oleg

**Comment by CBenghi** [comment]
Performances of the WPF component can be slow with extremely large models.
At the moment XbimXplorer attempts to display every single element in the model, wich can be very onerous for piping/electrical/mechanical/reinforcement elements.

I'd suggest into LayerStylers or filtering to simplify the requirements for the GPU and drop some of these elements out of the scene.
