### ISSUE TITLE
What connects between XbimTreeview, DrawingControl3D, IfcMetaDataControl and main view?

### ISSUE THREAD

**Issue by jojobs** [xBimTeam/XbimWindowsUI#34]
Hi @andyward, @martin1cerny, @CBenghi,

I would like to use Xbim.Presentation in my IFC project. In my new WPF project, I have implemented all required functionalities from sample XplorerMainWindow.xaml. 

Now I can see all three UI items (XbimTreeview, DrawingControl3D, IfcMetaDataControl ) showing correctly in my main view. However now I am loosing the interconnection between these three UI components, means if I select an item in XbimTreeview, it is not highlighting that in DrawingControl3D.

As per my understanding, the interconnection between four work if I create a dependency property in my view (IfcMyWindow).
```

public IPersistEntity SelectedItem
{
	get { return (IPersistEntity)GetValue(SelectedItemProperty); }
	set { SetValue(SelectedItemProperty, value); }
}

public static readonly DependencyProperty SelectedItemProperty =
	DependencyProperty.Register("SelectedItem", typeof(IPersistEntity), typeof(IfcMyWindow),
								new UIPropertyMetadata(null, OnSelectedItemChanged));


private static void OnSelectedItemChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
{
	var mw = d as IfcMyWindow;
	if (mw != null && e.NewValue is IPersistEntity)
	{
		var label = (IPersistEntity)e.NewValue;
		mw.EntityLabel.Text = label != null ? "#" + label.EntityLabel : "";
	}
	else if (mw != null) mw.EntityLabel.Text = "";
}
```

Could you please tell me what I am missing?

Best regards,
Jojo

**Comment by theebow** [comment]
if it can help you, i've been working last year on a little application demo consist in DrawingControl3D entity selection from a ifcProduct list datagridview...and if a correctly remember, i used something that : 
 
```
 IPersistIfcEntity w = myIfcMOdel.Instances.ofType<XXX>().where(p => p.EntityLabel == entityLabelToSelect).First();
 drawingControl3D1.Selection.Add(w);
 drawingControl3D1.SelectedEntity = w;
```

**Comment by CBenghi** [comment]
in general what you do is ok but then you have to ensure that the binding of controls in xaml points to that property e.g.
`SelectedEntity="{Binding Path=SelectedItem, ElementName=MainWindow, Mode=TwoWay}"`
or similar, depending on your xaml

To pick up from @theebow suggestion, that code should not be required unless you want to automate the change of the selected element, and in general it could be simplified as follows:

`var w = myIfcMOdel.Instances[entityLabelToSelect]`

this should more more efficient.

**Comment by jojobs** [comment]
Thanks very much Theebow and Claudio.
