### ISSUE TITLE
[Suggestion]Hide/Show entity

### ISSUE THREAD

**Issue by theebow** [xBimTeam/XbimWindowsUI#37]
To add Show/hide entity funtionality i overrided SurfaceLayerStyler class
into a SurfaceLayerStylerWithExcludeEntities class based on this model :

```
    public class SurfaceLayerStylerWithExcludeEntities : SurfaceLayerStyler, ILayerStyler
    {
       public new event ProgressChangedEventHandler ProgressChanged;

        public List<int> ExcludeLabelEntityList
        {
            get;
            set;
        }

        public new XbimScene<WpfMeshGeometry3D, WpfMaterial> BuildScene(IModel model, XbimMatrix3D modelTransform, ModelVisual3D opaqueShapes, ModelVisual3D transparentShapes,
            List<Type> exclude = null)

        .......
```

the goal is to override BuildScene function by replacing : 

```
var shapeInstances = geomReader.ShapeInstances
                        .Where(s => s.RepresentationType == XbimGeometryRepresentationType.OpeningsAndAdditionsIncluded
                                    && 
                                    !excludedTypes.Contains(s.IfcTypeId));

```

by

```
var shapeInstances = geomReader.ShapeInstances
                        .Where(s => s.RepresentationType == XbimGeometryRepresentationType.OpeningsAndAdditionsIncluded
                                    &&
                                    !excludedTypes.Contains(s.IfcTypeId)
                                    &&
                                    ((ExcludeLabelEntityList != null)?!ExcludeLabelEntityList.Contains(s.IfcProductLabel):true));
```

to do this i need to change **private** SurfaceLayerStyler properties to **protected**
this is available for : 
- protected static WpfMeshGeometry3D GetNewStyleMesh(
- protected static WpfMaterial GetWpfMaterial(
- protected WpfMaterial GetWpfMaterialByType(
- protected static readonly ILog Log = 

Are you agree with that ?

**Comment by CBenghi** [comment]
Hello @theebow,
I've published a few changes for this in a833e9d4cdd1898af66dc6b3891e242e97bac879.
You'll notice I've refactored the code to expose a protected GetShapeInstancesToRender() function.
This should make it much easier and maintainable for you to override the code.
I've also marked the other functions as protected as you requested.
Hope this helps,
Claudio

**Comment by theebow** [comment]
@CBenghi 
GetShapeInstancesToRender() function is a really good idea to avoid BuildScene overriding

But for working fine could you please put her as **virtual** so that i put mine **override**, otherwise when i'm in SurfaceLayerStyler::BuildScene, this is SurfaceLayerStyler::GetShapeInstancesToRender calling and not MineLayerStyler::GetShapeInstancesToRender, even if new syntax prefix

best regards

if you want to test with another SurfaceLayerStyler : 

```
    public class SurfaceLayerStylerWithExcludeEntities : SurfaceLayerStyler
    {
        public SurfaceLayerStylerWithExcludeEntities()
        {
            ExcludeLabelEntityList = new List<int>();
        }

        public List<int> ExcludeLabelEntityList
        {
            get;
            set;
        }

        protected override IEnumerable<XbimShapeInstance> GetShapeInstancesToRender(IGeometryStoreReader geomReader, HashSet<short> excludedTypes)
        {
            var shapeInstances = geomReader.ShapeInstances
                .Where(s => s.RepresentationType == XbimGeometryRepresentationType.OpeningsAndAdditionsIncluded
                            &&
                            !excludedTypes.Contains(s.IfcTypeId)
                                    &&
                            ((ExcludeLabelEntityList != null)?!ExcludeLabelEntityList.Contains(s.IfcProductLabel):true));

            return shapeInstances;
        }
    }

```

**Comment by metorm** [comment]
@theebow 

I am working on Show/hide entity funtionality too.

I have just studies `BuildScene` and `GetShapeInstancesToRender`. It seems that  `BuildScene` is called only once when loading the file. But now I need to hide/show entries dynamically depending on user click.

May be it will be too slow to build scene again and again. Is there any other route to do this? Thank you!

**Comment by theebow** [comment]
@metorm 

Hi,
i don't think, i did it with an override surfaceLayer class wich can keep entity to hide
and update view on loadGeometry (it look very faster)

here is my surfaceLayerWithExcludeEntities file (Rename .TXT by .CS) : 
[SurfaceLayerStylerWithExcludeEntities.txt](https://github.com/xBimTeam/XbimWindowsUI/files/691424/SurfaceLayerStylerWithExcludeEntities.txt)
[ILayerStyler.txt](https://github.com/xBimTeam/XbimWindowsUI/files/691425/ILayerStyler.txt)

and here my DrawingControl3D you can merge with yours (Rename again .txt by .cs 😉  )

[DrawingControl3D.xaml.txt](https://github.com/xBimTeam/XbimWindowsUI/files/691427/DrawingControl3D.xaml.txt)


in my application : 
```
        public void ViewerHideSelectedEntity()
        {
            if (CtrlViewer3D == null || IfcStore == null)
                return;

            if ((CtrlViewer3D.DefaultLayerStyler is SurfaceLayerStylerWithExcludeEntities) == false)
            {
                System.Diagnostics.Debug.Assert(false, "can be used only with SurfaceLayerStylerWithExcludeEntities ");
                return;
            }

            if (((SurfaceLayerStylerWithExcludeEntities)CtrlViewer3D.DefaultLayerStyler).ExcludeLabelEntityList == null)
            {
                ((SurfaceLayerStylerWithExcludeEntities)CtrlViewer3D.DefaultLayerStyler).ExcludeLabelEntityList = new List<int>();
            }

            foreach (IPersistEntity ent in CtrlViewer3D.Selection)
            {
                ((SurfaceLayerStylerWithExcludeEntities)CtrlViewer3D.DefaultLayerStyler).ExcludeLabelEntityList.Add(ent.EntityLabel);
            }

            CtrlViewer3D.LoadGeometry(IfcStore, null, DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
        }

        public void ViewerHideSelectedEntityType()
        {
            if (CtrlViewer3D == null || IfcStore == null)
                return;

            if (CtrlViewer3D.ExcludedTypes == null)
                CtrlViewer3D.ExcludedTypes = new List<Type>()
                {
                    typeof(IIfcSpace)
                };

            foreach (IPersistEntity ent in CtrlViewer3D.Selection)
            {
                Type t = ent.GetType();
                if (CtrlViewer3D.ExcludedTypes.Contains(t) == false)
                {
                    CtrlViewer3D.ExcludedTypes.Add(t);
                }
            }

            CtrlViewer3D.LoadGeometry(IfcStore, null, DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
        }
        public void ViewerResetHideEntity()
        {
            if (CtrlViewer3D == null || IfcStore == null)
                return;

            if ((CtrlViewer3D.DefaultLayerStyler is SurfaceLayerStylerWithExcludeEntities) == false)
                return;

            ((SurfaceLayerStylerWithExcludeEntities)CtrlViewer3D.DefaultLayerStyler).ExcludeLabelEntityList.Clear();

            CtrlViewer3D.LoadGeometry(IfcStore, null, DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
        }
        public void ViewerResetHideEntityType()
        {
            if (CtrlViewer3D == null || IfcStore == null)
                return;

            CtrlViewer3D.ExcludedTypes = new List<Type>
            {
                typeof (IfcSpace)
            };

            CtrlViewer3D.LoadGeometry(IfcStore, null, DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
        }
        public void ViewerShowIfcSpace()
        {
            if (CtrlViewer3D == null || IfcStore == null)
                return;

            if (CtrlViewer3D.ExcludedTypes == null)
                CtrlViewer3D.ExcludedTypes = new List<Type>();

            for (int i = 0; i< CtrlViewer3D.ExcludedTypes.Count; i++)
            {
                Type t = CtrlViewer3D.ExcludedTypes[i];
                if (t == typeof(IfcSpace))
                {
                    CtrlViewer3D.ExcludedTypes.RemoveAt(i);
                    break;
                }
            }

            CtrlViewer3D.LoadGeometry(IfcStore, null, DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
        }
        public void ChangeColorSelectedEntity()
        {
            if (CtrlViewer3D == null || IfcStore == null)
                return;

            ColorDialog dlg = new ColorDialog();
            if (dlg.ShowDialog() != DialogResult.OK)
                return;

            foreach (IPersistEntity ent in CtrlViewer3D.Selection)
            {
                string tt = ent.ExpressType.Name;
                CtrlViewer3D.ForcingColorEntityTo(ent, new XbimColour(dlg.Color.Name, (int)dlg.Color.R, (int)dlg.Color.G, (int)dlg.Color.B));
            }

            CtrlViewer3D.ReloadModel(DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
        }
        public void ResetChangeColorSelectedEntity()
        {
            if (CtrlViewer3D == null || IfcStore == null)
                return;

            foreach (IPersistEntity ent in CtrlViewer3D.Selection)
            {
                CtrlViewer3D.ResetForcingColorEntity(ent);
            }

            CtrlViewer3D.ReloadModel(DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
        }
        public void ChangeTransparencySelectedEntity(float val)
        {
            if (CtrlViewer3D == null || IfcStore == null)
                return;

            foreach (IPersistEntity ent in CtrlViewer3D.Selection)
            {
                CtrlViewer3D.ForcingTransparencyEntityTo(ent, val);
            }

            CtrlViewer3D.ReloadModel(DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
        }
        public void ResetChangeTransparencySelectedEntity()
        {
            if (CtrlViewer3D == null || IfcStore == null)
                return;

            foreach (IPersistEntity ent in CtrlViewer3D.Selection)
            {
                CtrlViewer3D.ResetForcingTransparencyEntityTo(ent);
            }

            CtrlViewer3D.ReloadModel(DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
        }
        public void ResetAllChangeColorTransparency()
        {
            if (CtrlViewer3D == null || IfcStore == null)
                return;

            CtrlViewer3D.ResetAllForcingColor();

            CtrlViewer3D.ReloadModel(DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
        }

```

hope it can help you 😉

**Comment by metorm** [comment]
@theebow 

You are so kind. I am studying your code. Newbie to WPF custom controls,, it may take days...

**Comment by metorm** [comment]
You are so kind. 😀

I am studying your code. Newbie to WPF custom controls, it may take days...

**Comment by metorm** [comment]
Hi @theebow , I have already implemented hide/show entities dynamically. You are right, reloading the model finishes real time. The time taken to open a new file is spent on parsing, and `IfcStore` can be seen as a struct to store parsing results.

In addition, I encountered selection issue, which may be similar to the issue you had met when trying to load *.wexBIM file. The issue was caused by a `null` `Model` object. I think I can work out a way to perfectly load *.wexBIM file.

I noticed that you have several function named `ForcingColorEntityTo***`, could you show me your implementation in `DrawingControl3D.xaml.cs` or any other files? I also need to change color of entities, I guess I shall modify `LoadGeometry` to change color of entities, but the code in `LoadGeometry` is a little confusing ...

**Comment by theebow** [comment]
Hi, 
re-read please my post, i have provided DrawingControl3D CS file and had explained you :  see "**in my application**" (at the end of the post) to copy the code you have to insert into your form

ps: note that in my code, CtrlViewer3D is a DrawingControl3D  instance
;)

**Comment by metorm** [comment]
@theebow 

It seems you have implemented `ForcingColorEntityTo***` in your `SurfaceLayerStyler` class, which you didn't post.

Sorry about my last post (which is incorrect). I mean, I shall modify `BuildScene` function, but the code is a little confusing. In `BuildScene` function I cannot find a perfect place to iterate all geometries and see if it needs a costumed color. Will you please share your code?

**Comment by theebow** [comment]
[SurfaceLayerStyler.txt](https://github.com/xBimTeam/XbimWindowsUI/files/701951/SurfaceLayerStyler.txt)

oups sorry ^^

**Comment by metorm** [comment]
Got it, thanks ~

**Comment by GLFichera** [comment]
Hi @theebow. I'm studying about set transparency on a item and i see your code but it doesn't works. Can i use DrawingControl as DrawingControl3D istance?

**Comment by AyeChanAungThwin** [comment]
> @metorm
> 
> Hi, i don't think, i did it with an override surfaceLayer class wich can keep entity to hide and update view on loadGeometry (it look very faster)
> 
> here is my surfaceLayerWithExcludeEntities file (Rename .TXT by .CS) : [SurfaceLayerStylerWithExcludeEntities.txt](https://github.com/xBimTeam/XbimWindowsUI/files/691424/SurfaceLayerStylerWithExcludeEntities.txt) [ILayerStyler.txt](https://github.com/xBimTeam/XbimWindowsUI/files/691425/ILayerStyler.txt)
> 
> and here my DrawingControl3D you can merge with yours (Rename again .txt by .cs 😉 )
> 
> [DrawingControl3D.xaml.txt](https://github.com/xBimTeam/XbimWindowsUI/files/691427/DrawingControl3D.xaml.txt)
> 
> in my application :
> 
> ```
>         public void ViewerHideSelectedEntity()
>         {
>             if (CtrlViewer3D == null || IfcStore == null)
>                 return;
> 
>             if ((CtrlViewer3D.DefaultLayerStyler is SurfaceLayerStylerWithExcludeEntities) == false)
>             {
>                 System.Diagnostics.Debug.Assert(false, "can be used only with SurfaceLayerStylerWithExcludeEntities ");
>                 return;
>             }
> 
>             if (((SurfaceLayerStylerWithExcludeEntities)CtrlViewer3D.DefaultLayerStyler).ExcludeLabelEntityList == null)
>             {
>                 ((SurfaceLayerStylerWithExcludeEntities)CtrlViewer3D.DefaultLayerStyler).ExcludeLabelEntityList = new List<int>();
>             }
> 
>             foreach (IPersistEntity ent in CtrlViewer3D.Selection)
>             {
>                 ((SurfaceLayerStylerWithExcludeEntities)CtrlViewer3D.DefaultLayerStyler).ExcludeLabelEntityList.Add(ent.EntityLabel);
>             }
> 
>             CtrlViewer3D.LoadGeometry(IfcStore, null, DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
>         }
> 
>         public void ViewerHideSelectedEntityType()
>         {
>             if (CtrlViewer3D == null || IfcStore == null)
>                 return;
> 
>             if (CtrlViewer3D.ExcludedTypes == null)
>                 CtrlViewer3D.ExcludedTypes = new List<Type>()
>                 {
>                     typeof(IIfcSpace)
>                 };
> 
>             foreach (IPersistEntity ent in CtrlViewer3D.Selection)
>             {
>                 Type t = ent.GetType();
>                 if (CtrlViewer3D.ExcludedTypes.Contains(t) == false)
>                 {
>                     CtrlViewer3D.ExcludedTypes.Add(t);
>                 }
>             }
> 
>             CtrlViewer3D.LoadGeometry(IfcStore, null, DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
>         }
>         public void ViewerResetHideEntity()
>         {
>             if (CtrlViewer3D == null || IfcStore == null)
>                 return;
> 
>             if ((CtrlViewer3D.DefaultLayerStyler is SurfaceLayerStylerWithExcludeEntities) == false)
>                 return;
> 
>             ((SurfaceLayerStylerWithExcludeEntities)CtrlViewer3D.DefaultLayerStyler).ExcludeLabelEntityList.Clear();
> 
>             CtrlViewer3D.LoadGeometry(IfcStore, null, DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
>         }
>         public void ViewerResetHideEntityType()
>         {
>             if (CtrlViewer3D == null || IfcStore == null)
>                 return;
> 
>             CtrlViewer3D.ExcludedTypes = new List<Type>
>             {
>                 typeof (IfcSpace)
>             };
> 
>             CtrlViewer3D.LoadGeometry(IfcStore, null, DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
>         }
>         public void ViewerShowIfcSpace()
>         {
>             if (CtrlViewer3D == null || IfcStore == null)
>                 return;
> 
>             if (CtrlViewer3D.ExcludedTypes == null)
>                 CtrlViewer3D.ExcludedTypes = new List<Type>();
> 
>             for (int i = 0; i< CtrlViewer3D.ExcludedTypes.Count; i++)
>             {
>                 Type t = CtrlViewer3D.ExcludedTypes[i];
>                 if (t == typeof(IfcSpace))
>                 {
>                     CtrlViewer3D.ExcludedTypes.RemoveAt(i);
>                     break;
>                 }
>             }
> 
>             CtrlViewer3D.LoadGeometry(IfcStore, null, DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
>         }
>         public void ChangeColorSelectedEntity()
>         {
>             if (CtrlViewer3D == null || IfcStore == null)
>                 return;
> 
>             ColorDialog dlg = new ColorDialog();
>             if (dlg.ShowDialog() != DialogResult.OK)
>                 return;
> 
>             foreach (IPersistEntity ent in CtrlViewer3D.Selection)
>             {
>                 string tt = ent.ExpressType.Name;
>                 CtrlViewer3D.ForcingColorEntityTo(ent, new XbimColour(dlg.Color.Name, (int)dlg.Color.R, (int)dlg.Color.G, (int)dlg.Color.B));
>             }
> 
>             CtrlViewer3D.ReloadModel(DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
>         }
>         public void ResetChangeColorSelectedEntity()
>         {
>             if (CtrlViewer3D == null || IfcStore == null)
>                 return;
> 
>             foreach (IPersistEntity ent in CtrlViewer3D.Selection)
>             {
>                 CtrlViewer3D.ResetForcingColorEntity(ent);
>             }
> 
>             CtrlViewer3D.ReloadModel(DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
>         }
>         public void ChangeTransparencySelectedEntity(float val)
>         {
>             if (CtrlViewer3D == null || IfcStore == null)
>                 return;
> 
>             foreach (IPersistEntity ent in CtrlViewer3D.Selection)
>             {
>                 CtrlViewer3D.ForcingTransparencyEntityTo(ent, val);
>             }
> 
>             CtrlViewer3D.ReloadModel(DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
>         }
>         public void ResetChangeTransparencySelectedEntity()
>         {
>             if (CtrlViewer3D == null || IfcStore == null)
>                 return;
> 
>             foreach (IPersistEntity ent in CtrlViewer3D.Selection)
>             {
>                 CtrlViewer3D.ResetForcingTransparencyEntityTo(ent);
>             }
> 
>             CtrlViewer3D.ReloadModel(DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
>         }
>         public void ResetAllChangeColorTransparency()
>         {
>             if (CtrlViewer3D == null || IfcStore == null)
>                 return;
> 
>             CtrlViewer3D.ResetAllForcingColor();
> 
>             CtrlViewer3D.ReloadModel(DrawingControl3D.ModelRefreshOptions.ViewPreserveCameraPosition);
>         }
> ```
> 
> hope it can help you 😉

It works! Sir, I need a drag selection of those ifcobjects in 3d view. Is that possible to do it? Or how can I do muliselect the same type by selecting a type?
