### ISSUE TITLE
[BUG]Canvas_mouseDown not found entity

### ISSUE THREAD

**Issue by theebow** [xBimTeam/XbimWindowsUI#38]
Hi all,

var hitObject = hit.ModelHit.GetValue(TagProperty);
sometimes return null when the mouse click seem to be on the edge of entity
as you can see below : 

Have joined the ifc file (please rename ".txt" ->".ifc" before as *.ifc are not allowed to be upload here)

![bugclickentity](https://cloud.githubusercontent.com/assets/17316045/19774919/fb68f008-9c6e-11e6-9470-a936c53de94f.PNG)

[Ch_Cable_Espace2.txt](https://github.com/xBimTeam/XbimWindowsUI/files/556372/Ch_Cable_Espace2.txt)

**Comment by theebow** [comment]
if it could help you, i have found this on the 
RayMeshGeometry3DHitTestResult hit = FindHit( ...) function
![bugclickentity2](https://cloud.githubusercontent.com/assets/17316045/19852031/378c4f7c-9f61-11e6-8a89-16e5975a090a.PNG)

**Comment by CBenghi** [comment]
Hi,
I've had a look at the selection function.
I'm not sure I fully reproduced the problem, but I've found a strange behaviour that might have to do with your issue.
I hope to complete a fix tomorrow and I'll ask for your feedback to see if it's fixed.
Thanks

**Comment by theebow** [comment]
Hi Claudio, thanks
i made a little video in this zip file and if you could replace DrawingControl3D and generic file by mine
you will get the functionanlity (HotEntity)...perhaps it could help you
regards

ps: do not pay attention on the debug code, have been trying to find the problem for monday ^^

[bughotentity.zip](https://github.com/xBimTeam/XbimWindowsUI/files/565922/bughotentity.zip)

**Comment by CBenghi** [comment]
Hello theebow,
I've just pushed a bugfix commit for this.
With the updated code I cannot reproduce the case in which an element is not selected on click.
I've not implemented your code, because our codebase had already been changed from your version, but it might be easy for you to merge the remote changes (git would do it thorough diff and retain your local changes with the remotes).
Could you have a look and see if the fix works for you? 
Thanks,
Claudio

**Comment by theebow** [comment]
Hi Claudio

Thanks for reactivity, i'm going to check all (posts) you have notified me ^^ , but for this it seem to be work fine 👍 
i'll be back as soon as i have checked everything

Thanks again
