### ISSUE TITLE
Customizing SpatialControl - tree view

### ISSUE THREAD

**Issue by jojobs** [xBimTeam/XbimWindowsUI#39]
Hi @CBenghi , @andyward, @martin1cerny ,

Thanks very much for your excellent work on this.

I would like to know, is there any way I can customize tree view. For example I need Walls instead of IfcWallStandardCase in the tree view. Is it possible?

Also it is possible to expand the tree on start?

Best regards,
Jojo

**Comment by martin1cerny** [comment]
Yes it is. If you want this to be a new feature of the view feel free to implement this functionality as an option (so the default functionality remains unchanged) and create pull request to contribute to the project. This kind of contribution is much appreciated.

Or you can grab the code with respect to our CDDL license and implement changes you need.

**Comment by jojobs** [comment]
Thanks very much for your reply Martin. Let me see how I can contribute...

**Comment by jojobs** [comment]
Hi @martin1cerny ,

Is there any way right now, I can at least remove the entity label from tree view?

Best regards,
Jojo

**Comment by martin1cerny** [comment]
Yes there is. My previous answer applies.

**Comment by jojobs** [comment]
Hi Martin,

Thanks very much for your reply.

Just to confirm, right now it is not possible, I have to build this as an option then publish or develop as per CDDL license. Correct me, if I am wrong?

Best regards,
Jojo

**Comment by martin1cerny** [comment]
Yes, you are right. It shouldn't be hard to change such a detail.
