### ISSUE TITLE
How to find the associated wall from Door

### ISSUE THREAD

**Issue by jojobs** [xBimTeam/XbimWindowsUI#40]
Hi @martin1cerny, @andyward, @CBenghi ,

I could not find any associations from door to wall. Could you please help me how to find the corresponding associated wall from a door?

My code is:

```
if(entitySelected is IfcDoor)
{
     IfcDoor ifcDoor = (IfcDoor)entitySelected;

//Find the Building Storey
     IfcBuildingStorey ifcBuildingStorey = (IfcBuildingStorey)ifcDoor.IsContainedIn;

//Find the wall that holds the door
-->
}
```

Is it my model issue?

Best regards,
Jojo

**Comment by martin1cerny** [comment]
This information might not be in your model at all or you might want to have a look at [IfcRelSpaceBoundary](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcproductextension/lexical/ifcrelspaceboundary.htm), [IfcRelVoidsElement](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcproductextension/lexical/ifcrelvoidselement.htm), [IfcRelFillsElement](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcproductextension/lexical/ifcrelfillselement.htm), [IfcRelReferencedInSpatialStructure](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcproductextension/lexical/ifcrelreferencedinspatialstructure.htm) and possibly [other](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifckernel/lexical/ifcrelationship.htm).

**Comment by jojobs** [comment]
Hi Martin,

You are correct. Since I have recreated the model using the code I have supplied (https://github.com/xBimTeam/XbimEssentials/issues/57) the model was missing FillsVoids, so I could not find.

Thanks very much once again.
Best regards,
Jojo
