### ISSUE TITLE
Duplication in the plugin's menu

### ISSUE THREAD

**Issue by bakongi** [xBimTeam/XbimWindowsUI#41]
If click to load plugins several times

![settingswindow](https://cloud.githubusercontent.com/assets/23183261/19880863/1bc4c560-a02b-11e6-8117-9ba02ef99a67.jpg)

![xbim explorer_bug1](https://cloud.githubusercontent.com/assets/23183261/19880787/6a5f284c-a02a-11e6-9f38-0c79b53376ee.png)
![xbim explorer_bug1](https://cloud.githubusercontent.com/assets/23183261/19880820/be26ee60-a02a-11e6-8ac7-efcfd4a01de8.jpg)

**Comment by CBenghi** [comment]
Yes, it's a known issue.
I've started yesterday revising the plugin management functions in the develop branch.
The aim is to allow the deployment and updated of plugins from a centralised repository.
I hope to finish this by the end of the week. 
The "Load now" button is going to disappear when I've finished.
Thanks!

**Comment by CBenghi** [comment]
Hello, the load now button has been removed (in the develop branch for the time being).
I'll put a load button for a individual plugins soon, making sure that hey are only loaded once.
Thanks for the heads up.
