### ISSUE TITLE
IfcWindow - Opening ht, opening width, head height

### ISSUE THREAD

**Issue by jojobs** [xBimTeam/XbimWindowsUI#43]
Hi @martin1cerny, @andyward, @CBenghi,

What is the best way to get  Opening element height, opening element width, head height from a window? My code is as shown below.
```
IfcWindow ifcWindow = (IfcWindow)entitySelected;
IfcRelFillsElement ifcRelFillsElement = ifcWindow.FillsVoids.FirstOrDefault();
IfcOpeningElement ifcOpeningElement = ifcRelFillsElement.RelatingOpeningElement;
IfcRelVoidsElement ifcRelVoidsElement = ifcOpeningElement.VoidsElements;
IfcWallStandardCase ifcWallStandardCase = (IfcWallStandardCase)ifcRelVoidsElement.RelatingBuildingElement;

WallName = ifcWallStandardCase.Name.ToString();
WindowHeight = ifcWindow.OverallHeight.Value;
WindowWidth = ifcWindow.OverallWidth.Value;

OpeningWidth = ??? (Eg: Rough Width in Revit)
OpeningHeight = ??? (Eg: Rough Ht in Revit)
HeadHeight= ???

```
Best regards,
Jojo

**Comment by theebow** [comment]
if it's like ifcFlowSEgment, there are some ways but not reliable
- 1 : parsing properties (if you know width/height/.. names 
- 2 : parsing Quantities (if there are exported)

they depend on ifc export quality/options/langage.... 

the only one reliable is geometry analysis

**Comment by jojobs** [comment]
@theebow,

Thanks very much. I will go will geometry analysis.

Best regards,
Jojo
