### ISSUE TITLE
Crash loading BCF module

### ISSUE THREAD

**Issue by theebow** [xBimTeam/XbimWindowsUI#45]
Hi the Team ;o)

Crash occurs while opening the "View"->"Setting" XBimXplorer menu

![crashloadingbcfeditormodule](https://cloud.githubusercontent.com/assets/17316045/20182175/37fe8ba2-a761-11e6-9cbd-7d44bb868cde.png)

There is no any "*.manifest" file in the output directory !?!

![crashloadingbcfeditormodule2](https://cloud.githubusercontent.com/assets/17316045/20182249/6e3d3fce-a761-11e6-8374-7634d7df5223.png)

**Comment by CBenghi** [comment]
Hello @theebow,
I think the error you are referring to had already been removed from the codebase when you posted.
Can you try again getting the latest codebase, lots of changes there in the past few days.
Thanks,
Claudio

**Comment by theebow** [comment]
Hi Claudio
Sorry for delay, i was out of service :)
it's ok after update
Thanks !
