### ISSUE TITLE
(enhancement) BCF plugin

### ISSUE THREAD

**Issue by bakongi** [xBimTeam/XbimWindowsUI#46]
I think, that placing BCF plugin to the right side will make it much more comfortable to use. Now we have to switch from one window (3D) to another (Bcf), which is not convenient

**Comment by CBenghi** [comment]
Hello bakongi,
you can move the window where you wish by dragging the window from the highlighted title
![image](https://cloud.githubusercontent.com/assets/5476273/20242576/230c558e-a901-11e6-8d36-4b49e182700d.png)
and dropping it on the highlighted icon 
![image](https://cloud.githubusercontent.com/assets/5476273/20242582/5f492f90-a901-11e6-92ca-7f340e2e04b7.png)

Your application will look like this:
![image](https://cloud.githubusercontent.com/assets/5476273/20242585/80e5d50e-a901-11e6-895f-07d33388c6c2.png)

Is this what you wanted to achieve?
Claudio

**Comment by bakongi** [comment]
Wow, yes this is what I wanted but there is a small inconvenience. Other plugins placed in **one** place with tabs with fixed minimum width but Bcf plugin made additional tab and window and takes up more space on the screen. On a screens with low resolution (1280x1024 for example) it will be a problem I think.

![screenshot_2016-11-13_11-52-01](https://cloud.githubusercontent.com/assets/23183261/20243944/88043faa-a998-11e6-95f1-87779874d392.png)
![screenshot_2016-11-13_11-42-53](https://cloud.githubusercontent.com/assets/23183261/20243946/8807137e-a998-11e6-91bf-c5393c5cd389.png)

**Comment by CBenghi** [comment]
A few notes:
1) When you drop the item there are several icons that you can drop onto.
These allow you to drop the BCF plugin on the same space of the mvdxml plugin. Try playing around with it a bit.
2) You can close the mvdxml plugin using the (x) button on its title bar.
3) You can minimise the mvdxml plugin with the small pin icon next to the (x).
4) You can prevent to load the mvdxml plugin completely through the setting page.
5) You can also hide the navigation bar on the left and properties bar with the pin icons.

Try a few of these options.

**Comment by bakongi** [comment]
Ok, I understand.  I just wanted to draw attention to the fact that the increase in the number of plug-ins may lead to congestion in the program interface like this:

![samples](https://cloud.githubusercontent.com/assets/23183261/20253722/4353b51e-aa58-11e6-9ca9-423bab833e9c.png)

and

![samples-2](https://cloud.githubusercontent.com/assets/23183261/20253855/4b54f452-aa59-11e6-9ef5-16f74a79e2b9.png)

For example other plugins is limited by right column and switching between them by tabs is very convenient. If you enable new plugin it just a new tab

in my humble opinion...

**Comment by theebow** [comment]
Please note before that is a stupid question 😄  
How did you do to simply load the BCF module in the tab just near the 3Dview one ?

**Comment by bakongi** [comment]
Point mouse to the tab. Click and hold left button. Move to :
![xxxx](https://cloud.githubusercontent.com/assets/23183261/21012039/524c1190-bd7e-11e6-9c7b-bd6d00ee27fd.jpg)

done
