### ISSUE TITLE
After "Dock as Tabbed Document" problem

### ISSUE THREAD

**Issue by bakongi** [xBimTeam/XbimWindowsUI#47]
Ok, this is a continue of the plugins story )) I was played with tabs as was recommended me in #43 issue and that's what I found:
After selecting on any tabbed plugin as "Dock as Tabbed Document" you can't display any other plugins except bcf-plugin And after closing such plugin you can't open it and other plugins (except bcf) anymore.

![1](https://cloud.githubusercontent.com/assets/23183261/20265189/ce52da96-aa99-11e6-9cef-2c47849fed21.jpg)

**Comment by CBenghi** [comment]
Long time without thinking of this, but I'm now working on a solution.
Best,
Claudio

**Comment by CBenghi** [comment]
I think it should be fixed with the commit referenced above.
