### ISSUE TITLE
MvdXML plugin can be loaded twice

### ISSUE THREAD

**Issue by bakongi** [xBimTeam/XbimWindowsUI#48]
MvdXML plugin can be loaded twice

![2](https://cloud.githubusercontent.com/assets/23183261/20265624/5f233596-aa9c-11e6-8552-6a6c28f7e176.jpg)

**Comment by CBenghi** [comment]
Hello, 
yes, this behaviour is by design.
You can load multiple mvdxml files and check them against the same model.
To be precise you are not loading the plugin multiple times, but only showing multiple instances of the UI.
I hope this helps,
Claudio
