### ISSUE TITLE
Can't open ArchiCAD Reference File anymore

### ISSUE THREAD

**Issue by BjDi** [xBimTeam/XbimWindowsUI#58]
With the newest Version (I pulled today on 19.01.2017), I can't open a Reference IFC File we got from ArchiCAD.
[IFC Referenz_Bauteile_ORCA.zip](https://github.com/xBimTeam/XbimWindowsUI/files/716533/IFC.Referenz_Bauteile_ORCA.zip)
Furthermore, if you can open it and zoom and rotate the model (I hase been the case with a release from december), parts of the model clears away. You could also test it with the old version (3.1...).
Could you give me a hint or is it a bug. (It just happend with 2 files)

**Comment by SteveLockley** [comment]
Hi BjDi
I have updated the geometry engine in the develop branch and this resolves this problem. We will push this to Master in a few days when all regression test pass

**Comment by CBenghi** [comment]
![image](https://cloud.githubusercontent.com/assets/5476273/22396825/5863035e-e55b-11e6-8273-4ac2ed700e4a.png)
I've updated develop branch of WindowsUI to open the file with the new geometry engine.
Nice looking model, BTW.
