### ISSUE TITLE
Why Windows UI not showing pure openings in Tree view?

### ISSUE THREAD

**Issue by jojobs** [xBimTeam/XbimWindowsUI#60]
Hi @CBenghi, @LloydPickering, @martin1cerny,  @andyward, @benjymous,

I could not see "pure" openings (not part of Doors and Windows) in tree view?

Is it possible to make this visible in tree view and clickable in DrawingControl?

[JojoAddedOpeningAndBeam.zip](https://github.com/xBimTeam/XbimWindowsUI/files/912074/JojoAddedOpeningAndBeam.zip)

Best regards,
Jojo

**Comment by CBenghi** [comment]
Hello @jojobs,
I've lookeed at the file and there are only three openings in the file.
In terms of building breakdown they are not part of the relationships in IfcRelContainedInSpatialStructure of the storey, so it would not be obvious how to show them.
The treeview is easily hackable, if you wish to have them once you know the reqs.
Best,
Claudio

**Comment by jojobs** [comment]
Hi Claudio,
Great help, thanks very much. I have manually changed the IFC file and saw it is coming correctly in tree view.

One of my main customers all IFC files have the same problem, may be it is related to old Archicad they are using. In order to solve the problem, I am doing the following. I am sharing this for anyone who face the same problem in future. 

private static List<IfcOpeningElement> _availableStudOpenings; // private field

//Get those pure openings (not part of Doors or Windows)
_availableStudOpenings = new List<IfcOpeningElement>();
                    var ifcOpeningElements = new IfcProduct[0].Concat(ifcModel.Instances.OfType<IfcOpeningElement>());
foreach (IfcOpeningElement opening in ifcOpeningElements)
 {
      if (opening.HasFillings.Count() == 0)
      _availableStudOpenings.Add(opening);
}

//Add to ifcRelContainedInSpatialStructure.RelatedElements
foreach (IfcOpeningElement ifcOpeningElement in _availableStudOpenings)
 {
       ifcRelContainedInSpatialStructure.RelatedElements.Add(ifcOpeningElement);
}
