### ISSUE TITLE
Memory leak in IfcMetadataControl.xaml.cs

### ISSUE THREAD

**Issue by Silpelit** [xBimTeam/XbimWindowsUI#61]
Hi Team!

Recently i started to use the Xbim.Presentation to create a similar Xbim viewer solution, and by viewing bigger (50Mb+) IFCs, i noticed that every time i close and re-open the IFC, i get at least 30-40MB of memory leak. 

By doing a little performance analysis, i found that the IfcMetadataControl.xaml.cs holds a history object with a list of IPersistEntity instances. When the control receives a NULL model, it calls the clear method, but the clear method does not clear the history, and therefore, since the reference remains, the reference to the IfcStore also remains, and wont be collected by the GC.

Just a heads up, how i solved it is just that i extended the HistoryCollection class in Xbim.Presentation with a Clear() method and i also call that in the Clear() method of the IfcMetadataControl.xaml.cs

`

    private void Clear()
        {
            _objectProperties.Clear();
            _quantities.Clear();
            _properties.Clear();
            _typeProperties.Clear();
            _materials.Clear();
            _history.Clear();

            NotifyPropertyChanged("Properties");
            NotifyPropertyChanged("PropertySets");
        }

`
Thank you very much for the great solution for viewing IFCs!

**Comment by CBenghi** [comment]
Thanks for the heads up.
I've just pushed an update.

It would be great if you could do more review of the code, Presentation is far from optimised, and we would welcome PR for more complex code changes.

Best,
Claudio

PS, good luck with your viewer, we are always interested in the apps that are made with xbim, get in touch with your success story, we need it to evaluate Xbim's impact.
