### ISSUE TITLE
How to find the material layer thickness for IfcWall?

### ISSUE THREAD

**Issue by jojobs** [xBimTeam/XbimWindowsUI#64]
I know how to find the material layer thickness in IfcWallStandardCase. But what is the way to find the material layer thickness for an IfcWall?

Code to find the material layer for IfcWallStandardCase is as given below.
```
IfcMaterialLayerSetUsage ifcMaterialLayerSetUsage = (IfcMaterialLayerSetUsage)ifcWall.GetMaterial();
if (null != ifcMaterialLayerSetUsage)
{
	IfcMaterialLayerSet layerSet = ifcMaterialLayerSetUsage.ForLayerSet;
	if (null != layerSet)
	{
		IItemSet<IfcMaterialLayer> lstMaterLayer = layerSet.MaterialLayers;
		if (null != lstMaterLayer)
		{
			int noOfLayers = lstMaterLayer.Count();                     
			double totalThickess= layerSet.TotalThickness;
		}
	}
}
```

**Comment by CBenghi** [comment]
Is this what you are looking for?

```
IfcMaterialLayerSetUsage ifcMaterialLayerSetUsage = (IfcMaterialLayerSetUsage)ifcWall.GetMaterial();
if (null != ifcMaterialLayerSetUsage)
{
	IfcMaterialLayerSet layerSet = ifcMaterialLayerSetUsage.ForLayerSet;
	if (null != layerSet)
	{
		double totalThickess= layerSet.TotalThickness;
		var lstMaterLayer = layerSet.MaterialLayers;
		if (null != lstMaterLayer)
		{
			int noOfLayers = lstMaterLayer.Count();                     
			foreach (var eachLayer in lstMaterLayer)
			{
				var thisTh = eachLayer.LayerThickness;
			}
		}
	}
}
```

PS I wrote this without Visual Studio, so it might not compile, but you get the picture, I hope.

**Comment by jojobs** [comment]
Hi Claudio,
It works fine if I pass IfcWallStandardCase. But when I pass an IfcWall (Supertype of IfcWallStandardCase) ifcMaterialLayerSetUsage is null.

Some of the walls in the model are coming as
IFCWALL('2_NMvZRmX7pPr2cF3Gdm1T',#41,'Basic Wall:Dwelling Brick & Frame 240mm:1243271',$,'Basic Wall:Dwelling Brick & Frame 240mm:168456',#8824,#8944,'1243271');

**Comment by CBenghi** [comment]
This is probably a problem of the exporter omitting that information for the IfcWalls.
In principle the data structure is the same.

**Comment by jojobs** [comment]
Thanks v much Claudio,
Best regards,
Jojo
