### ISSUE TITLE
Ifc Rebar geometry worked in 2.4.1 doesnt in latest 4.x vresion 

### ISSUE THREAD

**Issue by jv112602** [xBimTeam/XbimWindowsUI#65]
in the ifc file attached the rebar of the piers done in revit worked in the old xbim explorer but not  the new. We are using the 4.x libraries in our project and get the same results as the new viewer. see picture as well

![image](https://cloud.githubusercontent.com/assets/10463983/26730619/2a055f92-4777-11e7-95d5-5cebd5d4fb5c.png)
[RVT_2016_Pier5.zip](https://github.com/xBimTeam/XbimWindowsUI/files/1048007/RVT_2016_Pier5.zip)

**Comment by CBenghi** [comment]
Thanks I'll extract a case study and put this as a bug in the Geometry engine.

**Comment by andyward** [comment]
Still broken in v5.

**Comment by Sentinel3d** [comment]
it still does not work, is there any update on this?

**Comment by CBenghi** [comment]
This got neglected... I'll try to give it a look.

**Comment by CBenghi** [comment]
As far as I can tell it's fixed both in v5 and v4.

This is V4
![image](https://user-images.githubusercontent.com/5476273/76408809-d4cd8a00-638d-11ea-929b-6006c6f3ca30.png)

And this is v5.1
![image](https://user-images.githubusercontent.com/5476273/76408841-e3b43c80-638d-11ea-8617-d9e97c7d13b9.png)

**Comment by Sentinel3d** [comment]
That is strange, i use the nuget packages of XBim and i do not see it in my 3D View, I have created a preview drawing where i draw lines out of the IfcReinforcingBar. but i do not see the geometry in 3D (only the cappings)

Inside the red circles you see the cappings (ends of the bar) of the IfcReinforcingBar
The purple lines in the "2D viewer" are the IfcReinforcingBar
![IfcReinforcingBarProblem](https://user-images.githubusercontent.com/6570499/76410979-2297c180-6391-11ea-9886-6e076678aacf.PNG)

Do i need to update some packages?
i use:
- Xbim.Common (v5.1.274)
- Xbim.Essentials (v5.1.274)
- Xbim.Geometry (v5.1.288)
- Xbim.Ifc (v5.1.274)
- Xbim.Ifc4 (v5.1.274)
- Xbim.ModelGeometry.Scene (v5.1.288)
- Xbim.WindowsUI (v5.1.169)

**Comment by CBenghi** [comment]
Do you want to try from the develop branch?
We have it on myget at https://www.myget.org/feed/Packages/xbim-develop

**Comment by Sentinel3d** [comment]
yes please! i like to try that

**Comment by CBenghi** [comment]
It's avalable to everybody.
See the "Compilation" section at http://docs.xbim.net/

You just need to add the following package sources to visual studio:
https://www.myget.org/F/xbim-develop/api/v3/index.json
https://www.myget.org/F/xbim-master/api/v3/index.json

**Comment by Sentinel3d** [comment]
Thanks! that did the trick. it works like a charm!
![image](https://user-images.githubusercontent.com/6570499/76425882-88dd0e00-63aa-11ea-8c74-432a90c0532f.png)
