### ISSUE TITLE
Question about hiding entities

### ISSUE THREAD

**Issue by GregorPavuna** [xBimTeam/XbimWindowsUI#67]
Hey, i've been wondering if there is any chance of hiding entities by entity label or if it's not, could you give me any hints how to do that? I'll post code afterwards here. Thanks!

Cheers

**Comment by CBenghi** [comment]
It's not simple at the moment to hide single elements in WindowsUI.

The reason behind this is a necessary speed optimisation connected with the use of Helix Toolkit for the 3D viewer.

Rather than being held in individual models, elements of the same style are grouped together to speed up the rendering process, so switching some off would require a regeneration of the model excluding the undesired elements.

This is possible in the LayerStyler class, however it's probably not an efficient way of doing it.
We've been thinking to drop helix and go directly to the graphics primitives for a while, but we have not yet identified an ideal solution.

Any advice is welcome.

**Comment by GregorPavuna** [comment]
Hey, i somehow managed to do it. It is not optimised yet. That will come if it gets in usage.

I made changes in DrawingControl3D.xaml.cs
`
private Dictionary<int, List<GeometryModel3D>> HiddenOpaquesGroup = new Dictionary<int, List<GeometryModel3D>>();
        private Dictionary<int, List<GeometryModel3D>> HiddenTransparentGroup = new Dictionary<int, List<GeometryModel3D>>();

public void HideEntity(int entitylabel)
        {
            
            RemoveVisualEntity(Opaques, entitylabel, HiddenOpaquesGroup);
            RemoveVisualEntity(Transparents, entitylabel, HiddenTransparentGroup);
        }

        public void ShowEntity(int entitylabel)
        {
            RestoreVisualEntity(Opaques, entitylabel, HiddenOpaquesGroup);
            RestoreVisualEntity(Transparents, entitylabel, HiddenTransparentGroup);
        }

protected void RemoveVisualEntity(ModelVisual3D mv, int entitylabel, Dictionary<int, List<GeometryModel3D>> hg)
        {
            if (mv.Children.Any())
            {
                var tmpGroup = ((ModelVisual3D)mv.Children[0]).Content as Model3DGroup;
                if (tmpGroup.Children.Any())
                {
                    foreach (GeometryModel3D item in tmpGroup.Children.ToList())
                    {
                        var obj = item.GetValue(TagProperty);
                        if (obj is XbimInstanceHandle)
                        {
                            if (((XbimInstanceHandle)obj).EntityLabel == entitylabel)
                            {
                                tmpGroup.Children.Remove(item);
                                if (!hg.ContainsKey(entitylabel))
                                {
                                    hg.Add(entitylabel, new List<GeometryModel3D>());
                                    hg[entitylabel].Add(item);
                                }
                                else if (!hg[entitylabel].Contains(item))
                                {
                                    hg[entitylabel].Add(item);
                                }
                            }
                        }
                        else if (obj is WpfMeshGeometry3D)
                        {
                            var field = ((WpfMeshGeometry3D)obj);
                            if (field.Meshes.Any())
                            {
                                var mesh = field.Meshes.FirstOrDefault();
                                if (mesh.EntityLabel == entitylabel)
                                {
                                    tmpGroup.Children.Remove(item);
                                    if (!hg.ContainsKey(entitylabel))
                                    {
                                        hg.Add(entitylabel, new List<GeometryModel3D>());
                                        hg[entitylabel].Add(item);
                                    }
                                    else if (!hg[entitylabel].Contains(item))
                                    {
                                        hg[entitylabel].Add(item);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        protected void RestoreVisualEntity(ModelVisual3D mv, int entitylabel, Dictionary<int, List<GeometryModel3D>> hg)
        {
            if (hg.Count > 0 && hg.ContainsKey(entitylabel) && hg[entitylabel].Count > 0 && mv.Children.Any())
            {
                var tmpGroup = ((ModelVisual3D)mv.Children[0]).Content as Model3DGroup;
                foreach (var item in hg[entitylabel])
                {
                    tmpGroup.Children.Add(item);
                }
                hg.Remove(entitylabel);
            }
        }

`

It works like a charm. I tried to animate it like: Hide all and than slowly appear them one by one with some delay between calls. It works.

Yeah i noticed Helix is quite complex. When i get a little bit more time i will have a look at the alternatives and if i get some good idea i will let you know.

**Comment by GregorPavuna** [comment]
I've got another question. Is there any reason that Unit is not filled up even though element has quantities and units are set?

**Comment by CBenghi** [comment]
I'm surprised.
Have you tried this on large models?
e.g. 200 Mb?

**Comment by GregorPavuna** [comment]
I don't have that big examples. If you can provide me that big IFC that would be nice.

**Comment by eugeniogo** [comment]
I'm sorry but there is  something  wrong: if you select some entities,  directly by tiping on them and then you hide all the elements, using your code, the selectd-highlighted ones will remain on the scene and this is correct. But if then you click on one of them, all elements will disappear

**Comment by CBenghi** [comment]
@GregorPavuna Gregor, can you put a PR in with your code on the develop branch.
I've not had time to look into this, but if you do I'll be happy to merge it.

**Comment by eugeniogo** [comment]
Hey, I further investigate and the problem is quite simple to solve:
The selected objects don't have  blue-rendered faces  because  the program adds over each of them a blue mesh (this, as secondary issue,  in any case leads to an ugly flickering on the screen). But the problem is that the GregorPavuna routine temporily erases even the selected objects. When you toggle the selection queue by clicking on an object, the dummy blue faces are automatically erased and so all the elements fade away.
I solved the problem by investigating the Selection queue (data are in Selection._selection), at the end of the RemoveVisualEntity(...), and re-adding them to the Model. This is fairly fast.
In order the improve the speed of the RemoveVisualEntity, I had built before a Dictionary of the entity instances, and I have a random access to them.
The only problem is that you have to initialize the Dictionary at Model Loading. It takes 2 seconds with a 30 MBytes model, but after this the speed of the routine is very good.
But now another issue rises: the entities are grouped, in order to speed-up the graphical operations. In this way it is impossible to get the visibility at level of a single object. CBenghi informed us of this on September  4 2017.
I'm working for a CAE solution with models up to 200 MBytes and could try to split the elements. Do you think the speed would be too low?
In any case I can try: could you give me any suggestion on the way?
Thank you

**Comment by eugeniogo** [comment]
Hey,
I've splitted the meshes in this way: 

                     (file SurfaceLayerStyle.cs)

 ==>                  bool MeshesGrouped = false;  // if true, all works like before

                        //GET THE ACTUAL GEOMETRY 
                        MeshGeometry3D wpfMesh;
                        //see if we have already read it
                        if (UseMaps && repeatedShapeGeometries.TryGetValue(shapeInstance.ShapeGeometryLabel, out wpfMesh))
                        {
                            .......  (unchanged code)
                       }
                        else //we need to get the shape geometry
                        {
                                .......  (unchanged code)
                       }

                        if (UseMaps && shapeGeom.ReferenceCount > 1) //only store if we are going to use again 
                            {
                                    .......  (unchanged code)
                            }
       ==>             else if (MeshesGrouped) //it is a one off, merge it with shapes of same style
                            {
                                   .......  (unchanged code)
                             }
new routine==> else  // single meshes anf  it is a one off, merge it with shapes of same style 
                            {
                                var targetMergeMeshByStyle = meshesByStyleId[styleId];
                                if (shapeGeom.Format != (byte)XbimGeometryType.PolyhedronBinary)
                                    continue;
                                var transform = XbimMatrix3D.Multiply(shapeInstance.Transformation, modelTransform);
                                wpfMesh = new MeshGeometry3D();
                                wpfMesh.Read(shapeGeom.ShapeData, transform);

                                var mg = new GeometryModel3D(wpfMesh, materialsByStyleId[styleId]);

                                mg.SetValue(FrameworkElement.TagProperty,
                                           new XbimInstanceHandle(model, shapeInstance.IfcProductLabel, shapeInstance.IfcTypeId));
                                mg.BackMaterial = mg.Material;
                                mg.Transform = null;
                                if (materialsByStyleId[styleId].IsTransparent)
                                    tmpTransparentsGroup.Children.Add(mg);
                                else
                                    tmpOpaquesGroup.Children.Add(mg);
                            }
                        }
                    }

                    if (MeshesGrouped)                    {
                        foreach (var wpfMeshGeometry3D in meshesByStyleId.Values)
                        {
                            wpfMeshGeometry3D.EndUpdate();
                        }
                    }

 and all works fine: every entity is a single mesh

**Comment by GLFichera** [comment]
Hi @eugeniogo, I tried this code e work fine for remove entities. Then I modify the "remove entity" routine to try to change elements style like color and opacity. It work fine too but if i'd want apply these changes to all the entities it is very slow cause the foreach in "remove entities" that has many items to manage. There is a better way than split elements?

**Comment by eugeniogo** [comment]
I'm sorry, but the only way to do this is to have single meshes.
Of course you have to be careful to expand only those you need, and asap to restore the full meshes view.
In order to go faster, you can use the ReloadModel routine  and rebuil di scene
