### ISSUE TITLE
Illuminate some items a the same times?

### ISSUE THREAD

**Issue by GLFichera** [xBimTeam/XbimWindowsUI#73]
Hi. Is it possible illuminate some items at the same time?
I retrieve these items by means of filters in the code but i don't know how illuminate them.
![cattura](https://user-images.githubusercontent.com/33751786/33139470-acce4eb6-cfad-11e7-8c71-000c1d47505f.PNG)

**Comment by CBenghi** [comment]
You can look at the code in xbimxplorer, multiple selection happens with the ctrl click gesture.

**Comment by GLFichera** [comment]
In That image i did the ctrl click gesture. I want obtain the same result by click on a button

**Comment by CBenghi** [comment]
Yes, my point is to look at the code of xbimxplorer to see how that can be done.

**Comment by GLFichera** [comment]
Ok. I'm looking. Thank you

**Comment by CBenghi** [comment]
Hey @GLFichera,
if you have solved the issue, it would help the community if you could write here what you have done.
Even better write a small PR for the [xbimdocs](https://github.com/xBimTeam/xbimteam.github.io) repository.
