### ISSUE TITLE
To write content in IFC File

### ISSUE THREAD

**Issue by saumilajmera** [xBimTeam/XbimWindowsUI#75]
Hello XBim Team,

I wanted to know is there any way to write some content in the different objects of our opened IFC file 
 through Xbim Xplorer. ?

**Comment by CBenghi** [comment]
Not natively.
One way would be to create a plugin to do that.
What kind of changes are you thinking about?

**Comment by saumilajmera** [comment]
Hello, well as of now I have managed an separate XML file for storing user specific information w.r.t each element id. But I need to draw a layer of image over a model imported from IFC file. I am attaching a research paper's photograph for which I am developing a prototype application.
![img_20180206_134942__01](https://user-images.githubusercontent.com/33475443/35881020-16978f56-0b45-11e8-9dd0-7d977017d242.jpg)
![img_20180206_134956__01](https://user-images.githubusercontent.com/33475443/35881033-1b601544-0b45-11e8-8ffb-44c0a3fa574c.jpg)

**Comment by CBenghi** [comment]
The first step would be to make sense of the type of semantic data that you wish to add.
Once that is clear then it's very easy to add it through a plugin.
A more complicated feat would be to overlay the icons, but that's not impossible.

What is reference for the paper in picture?

**Comment by saumilajmera** [comment]
Hello if you can help me understanding the flow of Xbim Xplorer and code structure so that I can proceed with my development work on it. You can pass me a document or any reference link if you have any.

**Comment by CBenghi** [comment]
The current wpf implementation is based on the helix toolkit.
I'd suggest that you look int helix's examples to see what is the suggested practice for that.
I hope this helps.
