### ISSUE TITLE
Visualizing CSG Primitives in XBimXplorer

### ISSUE THREAD

**Issue by KonstantinHamm** [xBimTeam/XbimWindowsUI#78]
Hi there, 
I'm trying to visualize simple Geometries (Boxes, Cones, Cylinders and Spheres). So i thought displaying those geometries with CSG Primitives would be the right way. Unfortunately i ran into some problems. 
For Example when I want to create a sphere with this code:
```
private IfcGeometricRepresentationItem CreateIfcSphere(Geometry sphereGeometry, IfcStore model)
{
    var sphere = (SphereGeometry)sphereGeometry;
    return model.Instances.New<IfcSphere>(s => { s.Radius = sphere.Radius * 1000; });
}
```
and then attatching that IfcGeometricRepresentationItem to a ifcFlowTerinal via that code: 
```
private IfcFlowTerminal CreateDummyFlowterminal(IfcStore model, IfcGeometricRepresentationItem geometry)
{
    return model.Instances.New<IfcFlowTerminal>(ft =>
    {
		ft.IsTypedBy = model.Instances.New<IfcLightFixtureType>();
        var shapeRepresentation = model.Instances.New<IfcShapeRepresentation>(s =>
        {
            s.ContextOfItems = model.Instances.OfType<IfcGeometricRepresentationContext>().FirstOrDefault();
            s.Items.Add(geometry);
            s.RepresentationType = XbimRepresentationType.CSG.ToString();
            s.RepresentationIdentifier = XbimRepresentationIdentifierType.Body.ToString();
        });

        var productDefinitionShape = model.Instances.New<IfcProductDefinitionShape>(pds =>
        {
            pds.Representations.Add(shapeRepresentation);
        });

        ft.Representation = productDefinitionShape;
    });
}
```
I get these Error Messages from XbimXplorer and nothing is visualized: 
```
INFO	Xbim.ModelGeometry.Scene.Xbim3DModelContext
GeomScene: Xbim3DModelContext [Unable to find any Geometric Representation contexts with Context Type = model and Context Identifier = , using Context Type = 'Design' instead. NB This does not comply with IFC 2x3 or greater, the schema is IFC2X3]

ERROR	Xbim.Geometry.XbimGeometryCreator
EE001: Failed to create geometry #26 of type IfcSphere, General Error Creating IfcSphere, #26

INFO	Xbim.ModelGeometry.Scene.Xbim3DModelContext
GeomScene: #26=IfcSphere [Is an empty shape]
```
Are CSG Primitives not implemented properly in XbimXplorer or am I doing something wrong?
Maybe the CSG Primitives are the wrong way to implement, what i want to achieve?
Can anybody help me here?

**Comment by CBenghi** [comment]
Hello,
The issue is probably with the relations that you create in the file that might be missing the right elements in the schema.
I'd suggest that you start reading the document at http://docs.xbim.net/examples/proper-wall-in-3d.html
Then intervene to replace there the representation of your choice.
Ifc is generally more complex than people would assume.
Please open again if you still have problems after reading that.
Best,
Claudio
