### ISSUE TITLE
webxbim error in visual studio 2013

### ISSUE THREAD

**Issue by zhengcongyin** [xBimTeam/XbimWindowsUI#8]
I have tried to add the source code of webxbimUI in visual studio, I can not load the model and Json, and got a error "Failed to fetch binary data from server. Server code: 404'. This might be due to CORS policy of your browser if you run this as a local file". However, it works fine in Visual Studio 2010. Could you tell me how to fix this problem?
 Thanks,

Best,
Zhengcong

**Comment by CBenghi** [comment]
Hello,
I don't quite understand the problem you have.
I know most people are using Vs2013 for the development of the web viewer, and as far as I know it should all be working, if in doubt maybe download develop branch, which is the one generally under development.
Also it's not clear why you are posting this issue under the WindowsUI project. Can you clarify?
Thanks,
Claudio

**Comment by andyward** [comment]
This issue was moved to xBimTeam/XbimWebUI#34

**Comment by andyward** [comment]
This issue was moved to xBimTeam/XbimWebUI#35
