### ISSUE TITLE
Using 3D component in Winforms (Xbim.Presentation)

### ISSUE THREAD

**Issue by YauronBis** [xBimTeam/XbimWindowsUI#80]
Expected behavior:

    Using DrawingControl3D as component under vb.net project
    or
    Having a Visual Studio Diagram for xBim Xplorer clarification to be able to finish it myself.
    or
    A better segmentation in xBIM Geometry classes to let DrawingControl3D (and others visual class too) be standalone.

Actual behavior or exception details:

    xBIM Xplorer only exist in WPF
    DrawingControl3D looks having invisible link (dependancy property) to other classes to work fine.

Versions of xBIM Packages:

    xBIM Essentials: 4.0.7
    xBIM Geometry: 4.0.11

Minimal code (or steps) to reproduce the issue:

See below.

We have no competence in the xaml, an my compagny only use VB.Net. So ...
I created a sample VB.net winform project to test Xbim.Presentation.DrawingControl3D instance interrop under a HostElement Control. I just try to visually load an ifc sample file in, to evaluate our possibility of DrawingControl3D integration. After translating a very large part of the c # code, concerning the opening of content ifc, seeing my attempt not to display any geometry, I realize that the DrawingControl3D component only works through an eco-system of classes that I do not master. For example, we do not want to use the element lookup panel. We wish to be independent on this subject.

I admit to being lost because I do not understand what really represents the variable ModelProvider! And when a refresh is done, and this object is not part of my scope of execution, I do not know what to simulate its existance.

You could tell me, it would be simpler, to compile xBim explorer and integrate it in its entirety in an application panel with the winAPI User32.SetParent, set invisible part i do not need, but I think especially that by agreeing to load classes that I do not use, and I do not control, I'm going to overload the memory and hover over the subject.
Minimal file to reproduce the issue:

this sample project use devexpres... just to produice xplorer similitude like ribbon menu, status bar, but i must drop bin folder to pass under 10Mb. I hope it works.

[ECI_xBIM.zip](https://github.com/xBimTeam/XbimWindowsUI/files/2017380/ECI_xBIM.zip)

**Comment by YauronBis** [comment]
just tell me....

**Comment by CBenghi** [comment]
Hello @YauronBis,
I'm thinking to create a winform demo for this, but it's got to be next week.
I'm very busy at work recently.
Claudio

**Comment by YauronBis** [comment]
It's fine. I will waiting as much you need. I wish i could help... but i still don't know how to.

**Comment by CBenghi** [comment]
Hello @YauronBis,
I've pushed a demo app to the solution online with a recent commit on the develop branch.
Best,
Claudio
