### ISSUE TITLE
Show also not referenced element in Xbim explorer

### ISSUE THREAD

**Issue by WindingWinter** [xBimTeam/XbimWindowsUI#85]
Refer to this [ifc file](https://github.com/xBimTeam/XbimSamples/blob/master/BasicCreate/SampleHouse.ifc).

I found that in Xbim explorer, it is not showing "not referenced" tree node, unlike [another IFCViewer](http://www.ifcbrowser.com/).

Can also implement showing this "not referenced" tree node?
![not referecne element ifc viewer 2](https://user-images.githubusercontent.com/13161574/41644078-afcc5152-749f-11e8-8a4a-3777ee503c2a.png)
**IFC viewer interface**

![not reference elemented](https://user-images.githubusercontent.com/13161574/41644079-aff82426-749f-11e8-984c-8d533d9768ad.png)
**Xbim explorer interface**

**Comment by CBenghi** [comment]
Hello,
I'm not sure about the value of the plain list.
In some models there might be thousands of elements listed in that configuration, making the UI difficult to use.
Also, the description in the IFC viewer seems inaccurate as the elements listed there are not actually "not referenced" (for example the "Ground floor" element is listed there, but as you can see in the tree it's also displayed under the reference tree.
If it helps, Xplorer has methods to select and list any elements using the query tools in the "view->developer windows->commands" window.
Best,
Claudio
