### ISSUE TITLE
Click on Material tab will crash the Xbim explorer

### ISSUE THREAD

**Issue by WindingWinter** [xBimTeam/XbimWindowsUI#86]
If you open this ifc file in Xbim explorer, and you select the single wall, and then you click on the material tab, the program will crash.

Note that this ifc file is generated by running the [HelloWall example](https://github.com/xBimTeam/XbimSamples/tree/master/HelloWall) from XbimSamples.

[HelloWallIfc4.txt](https://github.com/xBimTeam/XbimWindowsUI/files/2118712/HelloWallIfc4.txt)

**Comment by CBenghi** [comment]
Noted, thanks.

**Comment by CBenghi** [comment]
The develop branch has been fixed.
Xplorer binaries should update automatically to 4.0.12-V0061 soon.
