### ISSUE TITLE
Unable to locate XBim Nuget packages

### ISSUE THREAD

**Issue by azura-vergo** [xBimTeam/XbimWindowsUI#9]
Hi,i`m a fresh man in github.
when i try to debug this project(XbimWindowsUI),the VS away tell me that it can`t find the metadata file“F:\XbimWindowsUI-master\XbimWindowsUI-master\Output\Release\Xbim.Presentation.dll”	F:\XbimWindowsUI-master\XbimWindowsUI-master\PluginBCF\CSC	xBIM BCF Plugin” 

i don`t know how to find this"Xbim.Presentation.dll",can you give me some advices.
thank you anyway

**Comment by andyward** [comment]
It sounds like the Nuget package restore is not working for you. Make sure you've got the latest Nuget Package manager (at least 2.7) so that dependencies are restored before the build. (i.e. got to `Tools -> Extensions and Updates` in Visual Studio and search for Nuget)

**Comment by andykazmaier** [comment]
Sounds like Andy is right.  You can see step by step instructions I posted on this earlier issue here:

https://github.com/xBimTeam/XbimWindowsUI/issues/5

**Comment by CBenghi** [comment]
Hi there.
It's also likely that you need to have the right nuget sources if you are downloading the latest code.
Add https://www.myget.org/F/xbim-develop/api/v2 and https://www.myget.org/F/xbim-master/api/v2 depending on the branch that your are compiling. Mine looks something like this:

![image](https://cloud.githubusercontent.com/assets/5476273/9721428/1d1f432a-5592-11e5-985c-7b0a6f6151eb.png)

I hope this helps

**Comment by azura-vergo** [comment]
Mr.andy, 
First of all ,thank you very much.
I had already get the laste NuGet(2.8),but it still can`t work.
when i try to run the xbimEplorer,it output some issue follow
![qq 20150910164614](https://cloud.githubusercontent.com/assets/8624914/9784064/638ccf44-57db-11e5-95ea-76f6cfbb4896.png)

**Comment by azura-vergo** [comment]
Mr.Andy  kazmaier thank you ver much
i had tried your method before,and it remind that " it can`t find version 3.1.8 of package Xbim.Essentials". you can see it in the pictrue follow
![qq 20150910164351](https://cloud.githubusercontent.com/assets/8624914/9784147/fabbe29c-57db-11e5-8662-7c4264d6ce26.png)

**Comment by andyward** [comment]
See @CBenghi 's reply above. You need to set up the MyGet packages sources since the version of the XBimXplorer code you have depends on Xbim Packages that are not yet published in Nuget.

E.g. You need **3.1.8** of Xbim.Esssentials but Nuget only has up to **3.0.20** (which is older)

![image](https://cloud.githubusercontent.com/assets/923699/9784191/9fced6e4-57a1-11e5-9c64-0608c4d95497.png)

Make sure you add these to your Nuget package sources

* https://www.myget.org/F/xbim-master/api/v2
* https://www.myget.org/F/xbim-develop/api/v2

as per Claudio's screenshot, and Nuget should pick up the newer packages.

**Comment by azura-vergo** [comment]
Mr.Andyward sorry for so late to reply you.
it still the same error
i had asked one of my friend,if he can deal with this error,i will send a massage to you
thank you for you respose

**Comment by azura-vergo** [comment]
hi again,still the same problem.
[1].i try to install xBIM Exchange from (https://www.myget.org/F/xbim-master/api/v2)
NuGet show me an error,
![xbimerror](https://cloud.githubusercontent.com/assets/8624914/9844495/502d8e98-5af6-11e5-8e6c-be80b0df3ce1.png)

[2]. all the project reference can not be checked,even i try to delete it and add it again.
![qq 20150914153721](https://cloud.githubusercontent.com/assets/8624914/9844570/dc388d84-5af6-11e5-887a-a4d7435a2a0a.png)

**Comment by andyward** [comment]
Please try getting the latest code (in master branch). For some reason the package versions have been pointing at non-existent Myget versions which is why I think you're seeing this. I've reverted the projects back to use the latest published Nuget versions so it should build now

**Comment by azura-vergo** [comment]
thank you andy.
i hava getting the latest code and it can work.
thank you very much

**Comment by andyward** [comment]
Good stuff!
