### ISSUE TITLE
Transparent A Single Wall

### ISSUE THREAD

**Issue by jookerq** [xBimTeam/XbimWindowsUI#91]
hi
i have a ifc file with with some walls & furniture.
when i use the IfcSurfaceStyleRendering Or IfcSurfaceStyleShading i makes all my walls transparent like this 
![image](https://user-images.githubusercontent.com/10785162/44000865-c41796fa-9e3c-11e8-9e1f-9ce601a0678d.png)

but i need a single wall to remain visible like this
![image](https://user-images.githubusercontent.com/10785162/44000876-0595e564-9e3d-11e8-9f4f-552546b4203d.png)

**Comment by CamChatHel** [comment]
Did you find a solution to this? I need the same...

**Comment by jookerq** [comment]
> Did you find a solution to this? I need the same...

yes plz follow this link https://stackoverflow.com/questions/50735087/how-to-properly-change-the-xbim-standard-wall-colour-in-wpf/57069961#57069961
