### ISSUE TITLE
(not) empty IFC model

### ISSUE THREAD

**Issue by johnnyontheweb** [xBimTeam/XbimWindowsUI#94]
Hi all,
I'm writing regarding the attached file. In all other BIM viewer I see a beam, with XbimExplorer (and Xbim libraries in general) I see nothing. I get the error:
`ERROR	Xbim.Geometry.XbimGeometryCreator
EE001: Failed to create geometry #33 of type IfcExtrudedAreaSolid, General Error Creating IfcExtrudedAreaSolid, #33`
The file was generated with XbimEssential v4, IFC2x3 format.

Can anyone tell what's wrong in reading the model with Xbim? I suspect Xbim wants some additional informations (IFCProducts?) that other readers can bypass.
[wex.zip](https://github.com/xBimTeam/XbimWindowsUI/files/2492247/wex.zip)

**Comment by johnnyontheweb** [comment]
This seems to be independent of the file, I believe this is a bug, since in XbimGeometry-master\Xbim.Geometry.Engine.Interop\XbimGeometryEngine.cs there's a call to Create like this:
`public IXbimGeometryObject Create(IIfcGeometricRepresentationItem ifcRepresentation)
        {
            return Create(ifcRepresentation, null);
        }`
Calling `IXbimGeometryObject Create(IIfcGeometricRepresentationItem ifcRepresentation, IIfcAxis2Placement3D objectLocation)` when objectLocation is null will cause a AccessViolationException. Can you fix this?

**Comment by andyward** [comment]
This is fixed in the v5.0 XbimGeometry. Close this off when we integrate the latest dependencies

**Comment by bekraft** [comment]
The IFC isn't IFC2x3 compliant (as the embedded validation states):

`Entity #17 (IfcShapeRepresentation) has validation failures.
	IfcShapeRepresentation.ContextOfItems is not optional.
	Issue of type EntityWhereClauses on IfcShapeRepresentation.WR21.
Entity #31 (IfcShapeRepresentation) has validation failures.
	IfcShapeRepresentation.ContextOfItems is not optional.
	Issue of type EntityWhereClauses on IfcShapeRepresentation.WR21.
Entity #45 (IfcShapeRepresentation) has validation failures.
	IfcShapeRepresentation.ContextOfItems is not optional.
	Issue of type EntityWhereClauses on IfcShapeRepresentation.WR21.
Entity #59 (IfcShapeRepresentation) has validation failures.
	IfcShapeRepresentation.ContextOfItems is not optional.
	Issue of type EntityWhereClauses on IfcShapeRepresentation.WR21.
Entity #66 (IfcRelAssociatesMaterial) has validation failures.
	IfcRelAssociatesMaterial.RelatingMaterial is not optional.
Entity #67 (IfcRelAssociatesMaterial) has validation failures.
	IfcRelAssociatesMaterial.RelatingMaterial is not optional.
Entity #75 (IfcShapeRepresentation) has validation failures.
	IfcShapeRepresentation.ContextOfItems is not optional.
	Issue of type EntityWhereClauses on IfcShapeRepresentation.WR21.
Entity #109 (IfcShapeRepresentation) has validation failures.
	IfcShapeRepresentation.ContextOfItems is not optional.
	Issue of type EntityWhereClauses on IfcShapeRepresentation.WR21.
Entity #130 (IfcShapeRepresentation) has validation failures.
	IfcShapeRepresentation.ContextOfItems is not optional.
	Issue of type EntityWhereClauses on IfcShapeRepresentation.WR21.
Entity #151 (IfcShapeRepresentation) has validation failures.
	IfcShapeRepresentation.ContextOfItems is not optional.
	Issue of type EntityWhereClauses on IfcShapeRepresentation.WR21.
Entity #185 (IfcShapeRepresentation) has validation failures.
	IfcShapeRepresentation.ContextOfItems is not optional.
	Issue of type EntityWhereClauses on IfcShapeRepresentation.WR21.
Entity #210 (IfcShapeRepresentation) has validation failures.
	IfcShapeRepresentation.ContextOfItems is not optional.
	Issue of type EntityWhereClauses on IfcShapeRepresentation.WR21.
Entity #235 (IfcShapeRepresentation) has validation failures.
	IfcShapeRepresentation.ContextOfItems is not optional.
	Issue of type EntityWhereClauses on IfcShapeRepresentation.WR21.
Entity #256 (IfcShapeRepresentation) has validation failures.
	IfcShapeRepresentation.ContextOfItems is not optional.
	Issue of type EntityWhereClauses on IfcShapeRepresentation.WR21.
Entity #283 (IfcWallStandardCase) has validation failures.
	Issue of type EntityWhereClauses on IfcWallStandardCase.WR1.
Entity #290 (IfcShapeRepresentation) has validation failures.
	IfcShapeRepresentation.ContextOfItems is not optional.
	Issue of type EntityWhereClauses on IfcShapeRepresentation.WR21.
`
It's more a question of being more failure tolerant to frequent IFC schema implementation issues

**Comment by johnnyontheweb** [comment]
Yes, the hidden suggestion in my post is definitely to be more tolerant - all other readers I tried works fine. Is that possible? Otherwise, IMHO this would be a limitation of xBIM libraries.
